fluxcd/website

layouts/partials/navbar.html

For debugging purposes I added the `is-active` class to the navbar dropdown menu, which makes the dropdown open upon page load. This is not the desired behavior for a dropdown.

Fix navbar dropdown issue

---

config.toml

To ease finding the right documentation.

Create dedicated links for Flux and Helm Op docs

---

static/install

Preview:
```
curl -sL https://deploy-preview-11--fluxcd.netlify.com/install | sh
Downloading fluxctl_darwin_amd64...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   142    0   142    0     0    348      0 --:--:-- --:--:-- --:--:--   348
100   610    0   610    0     0    965      0 --:--:-- --:--:-- --:--:--   965
100 43.3M  100 43.3M    0     0  8770k      0  0:00:05  0:00:05 --:--:-- 11.5M
Download complete!
Add fluxctl to your path with:
export PATH=$PATH:$HOME/.fluxcd/bin
Get started with Flux https://docs.fluxcd.io/en/stable/tutorials/get-started.html
```
Similar to:
```
curl -sL https://run.linkerd.io/install | sh
curl -sL https://run.solo.io/gloo/install | sh
curl -sSL https://cli.openfaas.com | sh …
```

Add fluxctl install script for Linux and Darwin

---

config.toml

@mewzherder rightly pointed out that the statement about maintenance mode went missing.
I realise that the "notification area" is getting very crowded now. Maybe we just merge this as is for now and then figure out a way have a news section that sources bits from somewhere else and takes up more clearly defined space, e.g. 3 stickied bits of info (like flagger-move, maintenance mode) plus the last 3 blogs posts...?

re add maintenance mode statement

---

config.toml
content/en/.gitignore
external-sources/fluxcd/community

This will give us `/security`, `/governance`, `/contributing`, as opposed to linking off to the `/f/community` repository.

create proper sub-pages for contributing, governance and security

---

config.toml

Fix "Get an Invite" slack link typo

---

config.toml

This fixes (most of) the sidebar links. See #121 for the remaining work.
Fixes: #140

Unset github_subdir - we pass 'en' in contentDir

---

content/en/docs/get-started.md
content/en/docs/gitops-toolkit/source-watcher.md
content/en/docs/guides/installation.md
content/en/docs/migration/flux-v1-migration.md

As we don't pass '-L' to curl, the redirect is not being followed.

Update install script URL

---

layouts/partials/navbar.html

Fixes: #173
I'm sure there are prettier ways to do this. Maybe somebody can illuminate me on how to do this in a more compact way.

Exclude navbar search on /blog/ and /docs/

---

content/en/docs/guides/image-update.md
content/en/docs/use-cases/gh-actions-auto-pr.md

Replaces fluxcd/flux2#1354
Document the GitHub Actions workflows that automate opening a pull request when automation pushes changes to a separate branch (the staging branch, in this case.)

GitHub Actions - auto pull-request workflow

---

hack/generate-adopters-pages.sh

Fix adopters section, so we can do
- https://fluxcd.io/adopters#flux-v1
- https://fluxcd.io/adopters#flux-v2
- https://fluxcd.io/adopters#flagger
This broke because we prepended with e.g. "1-..."

Fix adopters section

---

assets/scss/_index.scss

hide the description on doc pages

---

.gitignore

Fixes: #248
Refer to https://gist.github.com/subfuzion/db7f57fff2fb6998a16c or other for a global `gitignore` file.

Remove user-specific files from gitignore

---

content/en/docs/migration/helm-operator-migration.md

Fixed name of caCert key use as secretRef for a private HelmRepository, the right name of the key is caFile.

Fix CA ref in helm-operator-migration

---

content/en/docs/guides/monitoring.md

Documents [flux2#1399](https://github.com/fluxcd/flux2/pull/1399) which is the move from our monitoring stack to [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)

Update monitoring docs to kube-prometheus-stack

---

hack/generate-adopters-pages.py

This PR addresses this issue (and potential others):
I broke up the script into functions to make some of the inner workings easier to figure out. I also changed the indentation of the generated markdown and fixed the issue above: it was due to mismatch of opened/closed `card-pane` shortcodes.

make adopters page script more functional

---

content/en/docs/guides/monitoring.md

The port-forward needs to use the namespace `monitoring` since that's the [namespace created by the kube-prometheus-stack kustomization](https://github.com/fluxcd/flux2/blob/main/manifests/monitoring/kube-prometheus-stack/namespace.yaml#L4)

Update namespace of kubectl command

---

content/en/docs/get-started.md
external-sources/fluxcd/flux2
static/_redirects

- In title 'Get Started' guide
- In contributing document

Remove "Flux v2" mentions

---

content/en/docs/migration/timetable.md
hack/import-flux2-assets.sh
layouts/docs/baseof.html

Fixes: #178 
Modify import script for this. Docs layout as well, notable diff to `docsy` is:
```diff
--- themes/docsy/layouts/docs/baseof.html	2021-04-28 16:57:40.000000000 +0200
+++ layouts/docs/baseof.html	2021-05-25 17:07:32.433230910 +0200
@@ -13,10 +13,14 @@
<div class="col-12 col-md-3 col-xl-2 td-sidebar d-print-none">
{{ partial "sidebar.html" . }}
</div>
+          {{ if not .Params.hugeTable }}
<div class="d-none d-xl-block col-xl-2 td-toc d-print-none">
{{ partial "toc.html" . }}
</div>
<main class="col-12 col-md-9 col-xl-8 pl-md-5" role="main">
+          {{ else }}
+          <main class="col-12 col-md-12 col-xl-10 pl-md-5 " role="main">
+          {{ end }}
{{ partial "version-banner.html" . }}
{{ if not .Site.Params.ui.breadcrumb_disable }}{{ partial "breadcrumb.html" . }}{{ …
```

Don't show right sidebar if "hugeTable: true" is set

---

content/en/docs/guides/image-update.md

Patch the current documentation to allow continuation of line where required to create the docker-registry secret in the example.  Without this the example will not run due to a bash error.  
Output of error this fixes:
```
secret/ecr-credentials created (dry run)
/bin/bash: line 5: -o: command not found
error: no objects passed to apply
```

Update image-update.md to allow secret creation

---

content/en/docs/faq/_index.md

Another one thanks @juozasg – the bad link is here:
https://fluxcd.io/docs/faq/#what-are-the-differences-between-v1-and-v2
> comparison of Flux v1 and v2 features in the (migration FAQ).

Fix a broken link (v1 migration FAQ)

---

assets/scss/_buttons.scss
assets/scss/_index.scss
assets/scss/_variables_project.scss
assets/scss/blocks/_hero.scss
assets/scss/main.scss
content/en/_index.html
layouts/shortcodes/blocks/cncf.html

WIP for closing https://github.com/fluxcd/website/issues/109
Updates several sections to use flux branding colors. Fixes button colors and borders to follow the same color. Adds small drop shadows to the title text, links and the Get Started button in the hero section that make those items more distinct despite using similar colors. Updates link and link hover colors in all sections. Flagger green for the Flagger project box. 
Community and resources sections use $flux-gray: #2f2f2f.
These design choices need to reviewed/approved and two more items must be fixed before this PR is complete: 
> in the notes boxes, the code blocks have the same font colour as links
> the code blocks background could be greyish like we had in mkdocs, right now the contrast is huge

Front page color improvements

---

content/en/docs/faq/_index.md

Update the `kustomize build` flags in FAQ to match https://github.com/fluxcd/flux2/pull/1519 and https://github.com/fluxcd/kustomize-controller/pull/343

Update docs to Kustomize v4

---

netlify.toml

This ensures the pages are not labeled with `noindex, nofollow`.

Set `HUGO_ENV` for production build

---

content/en/docs/gitops-toolkit/source-watcher.md

- Bump prerequisites versions
- Show best-practice of using `utilruntime.Must` while registering
API schemes

Update source-watcher documentation

---

layouts/partials/hooks/body-end.html

Filter on Algolia custom search tags. This can be merged some time after this is landed: https://github.com/algolia/docsearch-configs/pull/4232

Reenable search on legacy docs

---

content/en/docs/faq/_index.md

Fix: fluxcd/image-reflector-controller#105
I'm not sure if there is anything we can do to make this better, if you got a truncated database log, you probably don't want to go on like everything is fine. It should land in CrashLoopBackOff, and you need to make sure there is enough memory for the operation to succeed. So, fixing it with a work-around and some documentation.

add Raspberry Pi FAQ - use a swap file

---

assets/scss/_index.scss

Fixes ["Other Flux projects" section items not centered](https://github.com/fluxcd/website/issues/324)
Sets 1140px max-width for all front page sections to keep the layouts fixed on ultra-wide screens.

Front page item centering

---

assets/scss/_index.scss
content/en/_index.html
layouts/shortcodes/blocks/community.html

Fixes https://github.com/fluxcd/website/issues/133
Reduced the size of the section by removing extra copy text and reducing icon size to 1x. Fixed the background to be $flux-gray (#2f2f2f). 
Switched to flexbox for individual items - the layout seems to flow well on large, medium and small screens.

Front page Community section styling

---

content/en/docs/guides/webhook-receivers.md

In our docs for Webhook Receivers, we explain very briefly that you can use LoadBalancer or Ingress rules to get events from outside the cluster into the notification controller. The doc then goes on to show only a LoadBalancer example.
This PR expands the example to show both. There are other related changes I think we can make to this doc, perhaps hold off on merging this until we've had a chance to talk it out and ascertain how many of my expectations are off-base or if there's something important I missed.

Add documentation for how to use Ingress+Receivers

---

content/en/legacy/flux/faq.md
content/en/legacy/flux/get-started.md

There are two broken links according to python `linkchecker`, they look like accidental migration issues related to new home for legacy docs.
Sorry for not catching these issues sooner.

Fix two broken links in legacy docs

---

assets/scss/blocks/_nav.scss
config.toml

Fixes: #371
A newer Docsy version will fix this and we can drop the override in `_nav.scss`.

Reenable foldable sidebar menu

---

assets/scss/blocks/_hero.scss
content/en/_index.html

This is a quick draft of some of the Flux facts, @scottrigby and I collected and some folks gave feedback on. I just tried to put it on the landing page without the general markup of the page exploding.

add flux facts to main page

---

content/en/docs/guides/webhook-receivers.md

I was reviewing the webhook guide part supporting Ingress, and I came across this error.
The service is not called `notification-webhook` it is called `webhook-receiver`.

flux-system service is called "webhook-receiver"

---

content/en/docs/installation.md
docker-support/Dockerfile

Resolves #406 
Also fixes the `make docker-preview`, which was failing with this cryptic message because of a missing `pathlib` import:
```
make: hack/gen-content.py: No such file or directory
```
(Someone must run `make docker-push` with push access to fluxcd/website in order to publish the fix, it might be time to implement some CI that verifies we haven't changed something in a way that breaks the docker-preview functionality, and to permit updating of the `website:hugo-support` image more simply, by anyone and with a pull request.)

Fix broken link azure

---

content/en/docs/use-cases/gh-actions-manifest-generation.md

Found a couple of broken links on [this](https://fluxcd.io/docs/use-cases/gh-actions-auto-pr/) page, while reading the docs. ;)

Fix broken links on "GitHub Actions Manifest generation" page

---

README.md
adopters/1-flux-v2.yaml
adopters/3-flux-v1.yaml
adopters/README.md
content/en/_index.html
content/en/docs/_index.md
content/en/docs/components/_index.md
content/en/docs/guides/sortable-image-tags.md

With moving the docs for f/flux and f/helm-operator
under /legacy it should be even clearer now that the
rest of the site is about the new version of flux:
f/flux2.
I left "v1" and "v2" in a couple of places where we
refer to migration and do e.g. feature comparisons.

De-emphasise "v2" in terminology somewhat

---

content/en/docs/guides/webhook-receivers.md

svc/webhook-receiver is listening on port 80 (not port 9292)

Fix error in webhook receiver guide

---

Makefile
docker-support/Dockerfile
netlify.toml

Unfortunately we specify hugo versions in too many places, with this PR I'll bring all of them up to the same version:
```cli
❯ git grep 0.86.0
Makefile:HUGO_VERSION               ?= 0.86.0
docker-support/Dockerfile:FROM fluxcd/website:hugo-0.86.0-extended
netlify.toml:  HUGO_VERSION = "0.86.0"
package-lock.json:      "version": "0.86.0",
package-lock.json:      "resolved": "https://registry.npmjs.org/hugo-extended/-/hugo-extended-0.86.0.tgz",
package.json:    "hugo-extended": "^0.86.0",
website on  update-hugo [$] via  v12.22.3 via 🐍 v3.8.10
❯ 
```

update hugo version everywhere

---

content/en/docs/migration/helm-operator-migration.md

We have a couple of places where Image Update Automation is mentioned as "still currently unsupported, wait for the Feature Parity milestone" – I do not think this is true anymore, since feature parity has already been announced several minor releases ago.

Image Update Automation is supported

---

content/en/blog/2021-05-31-june-update.md

The branding.cncf.io site has been redirected to a git repo, and these links to our branding and logos are broken now.

Fix bad link in june-update

---

content/en/docs/guides/sortable-image-tags.md

Signed-off-by: Frederik Baetens <baetens.fr@gmail.com>
The order of the sha & run number were swapped between the github actions workflow example and the pattern.

fix sortable image tag pattern for github run number example

---

content/en/docs/guides/sealed-secrets.md

As described here: https://github.com/bitnami-labs/sealed-secrets/issues/317#issuecomment-718608815 the standard controller name for kubeseal is sealed-secrets-controller and if you only use sealed-secrets you need to define another enrironment variable called: SEALED_SECRETS_CONTROLLER_NAME.
So as an alternative to my pull request you can also add the text for using this variable.

added the standard controller name for kubeseal

---

.github/workflows/lychee-cron.yaml
.github/workflows/lychee-pr.yaml
Makefile
assets/scss/_index.scss
content/en/.gitignore
content/en/_index.html
hack/import-calendar.py
layouts/shortcodes/blocks/calendar.html
requirements.txt

Read the cncf-flux-dev calendar (ical) and show the events in the upcoming month.
Fixes: #449
Things that still need doing:
---
~~- [ ] make sure everyone involved has access to the calendar~~ (moved to https://github.com/fluxcd/community/issues/113)
~~- [ ] hook up calendar include generation with daily cronjob~~ (should be handled by https://github.com/fluxcd/website/blob/main/.github/workflows/netlify.yml)
~~- [ ] figure out if we can link to the events in question... do we get the data in the ICS somewhere (Daniel)~~ - moved to #461
~~- [ ] make links clickable in the event description~~ - moved to #461
~~- [ ] have a mouse-over with event data (@juozasg + Daniel)~~ - moved to #461
~~- [ ] maybe convert to browser TZ(?)~~ - moved to #461

Read Flux meeting ical

---

content/en/resources.md

Not sure if I did this correctly or not, but please let me know @dholbach :)
Updated Leo's talk from Conf42 with YouTube video link (instead of conf reg page link): https://youtu.be/AyRhi92v9O0?t=40

Update resources video url

---

content/en/docs/faq.md

1. The example in the FAQ didn't work because the CoreDNS deployment is managed by EKS. EKS manages fields for affinity rules (see https://docs.aws.amazon.com/eks/latest/userguide/add-ons-configuration.html). This causes EKS to update the deployment once every 30 minutes (rolling upgrade) and flux will immediately revert that back, causing rolling upgrades to keep on happening on the cluster.
2. Another reason the example in the FAQ didn't work: this is an existing deployment deployed outside of Flux and we have to manage it differently as we must add the `selector` and `template` fields.
3. Changed the example to modify the `replicas` is this is a non-managed field and can be safely updated.

Update doc about CoreDNS addon patching

---

content/en/roadmap.md

Changes:
- add links to overarching issues for API consolidation and ACL
- mark migration guides as done

Update GA roadmap

---

assets/js/calendar.js
assets/scss/_index.scss
assets/scss/blocks/_blocks.scss
assets/scss/blocks/_calendar.scss
hack/import-calendar.py
layouts/partials/hooks/body-end.html

Instead of mousenter/mouseleave I'm using clicks on the calendar items to activate. This works with both touchscreen and mouse cursor devices. Please review the import-calendar.py changes. I'm doing some data cleaning up that maybe could be avoided by changing calendar data contents, but it should work and look neat with the existing data now.

Front page calendar details dropdowns

---

layouts/partials/sidebar-tree.html

We set  sidebar_search_disable=true  so we also don't want it in mobile view. We show it in our navbar at the top.
Fixes: #504

Don't show search box in sidebar

---

content/en/integrations.md

Add https://github.com/aws/eks-anywhere and https://github.com/weaveworks/eksctl to integrations.

Add Amazon EKS Anywhere to Flux integrations

---

assets/scss/_index.scss

100vw required for the carousel layout was sometimes producing a small empty margin on the right side of the page. This is an artifact of the browser calculation of viewport width when a vertical scrollbar is present. Hide horizontal scrollbar as a workaround.

Fix adopters carousel horizontal overflow scrollbar

---

layouts/partials/sidebar-tree.html

I was over-eager in #505 and removed the :hamburger: icon in mobile docs.
The actual diff over upstream `docsy` in our `sidebar-tree.html` is even smaller now:
```cli
❯ diff -u {themes/docsy/,}layouts/partials/sidebar-tree.html 
--- themes/docsy/layouts/partials/sidebar-tree.html	2021-07-20 18:13:59.000000000 +0200
+++ layouts/partials/sidebar-tree.html	2021-09-10 14:47:56.666177455 +0200
@@ -11,7 +11,6 @@
{{ else -}}
<div id="content-mobile">
<form class="td-sidebar__search d-flex align-items-center">
-    {{ partial "search-input.html" . }}
<button class="btn btn-link td-sidebar__toggle d-md-none p-0 ml-3 fas fa-bars" type="button" data-toggle="collapse" data-target="#td-section-nav" aria-controls="td-docs-nav" aria-expanded="false" aria-label="Toggle section navigation">
</button> …
```

bring back hamburger icon in mobile docs

---

content/en/docs/use-cases/helm.md

We do alot of direct linking to pages which can be accessed in the local file tree
This makes it harder to use other markdown linters
An assumption needs to be made for each link to /docs where the path ends with a / to
whether it's a _index.md file, or whether it's an actual markdown file named helmreleases.md
making this PR to test that changing said links to relative markdown links still works on netlify
Fixing the links on each of the pages could make for some good first issues
[✖] /docs/components/helm/helmreleases/#values-overrides
[✖] /docs/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize
[✖] /docs/components/kustomize/kustomization/#secrets-decryption
[✖] /docs/guides/mozilla-sops/
[✖] /docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.InstallRemed …

pr to test direct linking to markdown files in docs

---

hack/gen-content.py

Make sure to catch '(old-link)' and replace it with '(new-link)', so we don't expand the same link multiple times.

Fix rewriting of links

---

.github/workflows/build-push-hugo-image.yml
.github/workflows/build-push-hugo-support.yml
Dockerfile
Makefile

Fixes #522
This PR will make the `docker-push-hugo` and `docker-push-support` targets triggerable as `workflow_dispatch` actions, through the Github Actions workflow tab on GitHub.
I tested this out on the `kingdon` branch of same fork of the website repo, the results are here: https://hub.docker.com/r/kingdonb/website/tags?page=1&ordering=last_updated
You can set `image: kingdonb/website:hugo-support` in `okteto.yml` and run `okteto up` to see this in action right now (the rebuilt image is what is required to make the `okteto up` or `make docker-serve` targets function properly)

Add manual trigger targets for (support) docker image builds

---

content/en/docs/guides/image-update.md

Describe the new option that is available for AWS ECR authentication in the Image Update guide.
Related:
* fluxcd/image-reflector-controller#193
* Recently reported issue asking for better documentation of this feature: #601 
* fluxcd/image-reflector-controller#174

Add note about AWS Autologin to Image Update guide

---

content/en/docs/guides/mozilla-sops.md

The example IAM policy for AWS KMS integration is too wide for kustomize-controller which only really needs describe and decrypt. 
I've tested this by changing the policy in our dev environment, deleting a secret and seeing it be successfully applied the next reconcile.

sops: Use minimal, decrypt-only policy for AWS

---

content/en/docs/guides/webhook-receivers.md

1. responsiveness
2. fix broken links

docs(webhook-receivers.md): responsiveness

---

content/en/docs/guides/mozilla-sops.md

branch or tag are required arguments

Add missing branch arg to SOPS guide

---

Makefile
content/en/blog/2021-10-29-november-update.md
layouts/partials/page-meta-links.html
netlify.toml

Only partial which needed updating was `page-meta-links.html` (our diff is smaller now). Hugo updated its `tweet` shortcode syntax as well.
The diff can be seen here:
```diff
❯ diff -u {../docsy/,}layouts/partials/page-meta-links.html
--- ../docsy/layouts/partials/page-meta-links.html	2021-11-17 13:06:45.619795981 +0100
+++ layouts/partials/page-meta-links.html	2021-11-17 13:10:11.994037432 +0100
@@ -5,6 +5,7 @@
{{ $gh_subdir := ($.Param "github_subdir") -}}
{{ $gh_project_repo := ($.Param "github_project_repo") -}}
{{ $gh_branch := (default "master" ($.Param "github_branch")) -}}
+{{ $importedDoc := $.Param "importedDoc" | default "false" }}
<div class="td-page-meta ml-2 pb-1 pt-2 mb-0">
{{ if $gh_url -}}
{{ warnf "Warning: use of `github_url` is deprecated. For details see …
```

Update to most recent Hugo and Docsy

---

content/en/docs/guides/image-update.md

As a Flux 1 user, we did not have these abstractions, and no comments were needed.
This is better!
I was aware of neither kyaml nor any other approach to comment templating on Kubernetes,
This paragraph would have helped me, and I think it can help others.
Signed-off-by: Jim Van Fleet <jim@jimvanfleet.com>

Explain how to leverage image policy markers.

---

content/en/docs/installation.md

Adds a Bitbucket Server section to the bootstrap doc.
Ref: https://github.com/fluxcd/flux2/pull/2070
Signed-off-by: Soule BA <soule@weave.works>

Add Bitbucket Server bootstrap instructions to the install docs

---

content/en/docs/guides/mozilla-sops.md

Explains how to use age to encrypt with a git workflow.
Links to the existing doc.
Signed-off-by: Soule BA <soule@weave.works>

Add an age section to sops guide

---

adopters/1-flux-v2.yaml

Signed-off-by: Iñigo Iglesias <inigo.iglesias@alea.com>
Logo already present from flux-v1

Add Alea to adopters fluxv2

---

content/en/docs/get-started.md

This may prevent beginners from removing the indenting after pasting the code in place.

Describe the position to add patches more precise

---

content/en/docs/guides/monitoring.md

Supersed #669 
Co-authored-by: Frédéric Pégé <frederic.pege@gmail.com>
Signed-off-by: Stefan Prodan <stefan.prodan@gmail.com>

Use exported_namespace in Alertmanager examples

---

content/en/legacy/helm-operator/how-to/upgrade-to-ga.md

docs(upgrade-to-ga.md): Flux CD → Flux

---

content/en/docs/contributing/docs/some-background.md

fix broken link:
`./netlify.toml`
→
https://github.com/fluxcd/website/blob/main/netlify.toml
Co-authored-by: Daniel Holbach <daniel@weave.works>

docs(some-background.md): Flux CD → Flux

---

content/en/docs/installation.md

Add some details on the permissions needed to bootstrap pre-existing repositiories.
This is instead of the change suggested here https://github.com/fluxcd/flux2/pull/2197

Add permissions info for GitHub installation

---

content/en/docs/use-cases/jenkins.md

I am not much of a Groovy programmer, so when I wrote this I did not realize there was another way to do integer division.
This is just dense enough groovy syntax and hard to parse for chroma to balk at it, this resolves the issue from #698 in lieu of an upstream fix for alecthomas/chroma#588

Remove double division and cast

---

content/en/docs/guides/mozilla-sops.md

Update that section to reference the kustomize-controller doc, now that
we support hc-vault decryption directly in the controller code.
Signed-off-by: Soule BA <soule@weave.works>
Part of: https://github.com/fluxcd/flux2/issues/2308

Update the Mozilla SOPS decryption with HashiCorp Vault section

---

content/en/docs/guides/cron-job-image-auth.md
content/en/docs/guides/image-update.md

This pull request adds documentation for GCR/ACR auto-login Integration and also moves the docs on using cron jobs to a separate page.
Part of: https://github.com/fluxcd/flux2/issues/2308

Add docs for autologin(ACR/ECR/GCR)

---

content/en/docs/faq.md
content/en/docs/get-started.md
content/en/docs/guides/cron-job-image-auth.md
content/en/docs/installation.md
content/en/docs/security/_index.md

Changes:
- set min required version to Kubernetes 1.20.6 in install doc
- add Multi-tenancy lockdown section to install docs 
- add Signed Container Images section to the security doc
- add Software Bill of Materials section to the security doc
- add Pod Security Standard section to the security doc
Part of: https://github.com/fluxcd/flux2/issues/2308

Update docs for Flux v0.26.0

---

content/en/_index.html
content/en/docs/_index.md
content/en/docs/components/_index.md
content/en/docs/concepts.md
content/en/docs/get-started.md
content/en/docs/guides/_index.md
content/en/docs/use-cases/_index.md

On the typical path of a Flux user, they will read "GitOps Toolkit" a lot. In this PR I try to collect GOTK information more centrally, so that the flow of a Flux user ("I want to 	understand/install Flux") is interrupted less.
Also fix link on landing page - it was broken.
Re-use phrasing from https://github.com/fluxcd/community/blob/main/style-guide.md
Fixes: #587 
cc @priyanka-ravi

De-emphasise GitOps Toolkit somewhat

---

content/en/docs/guides/image-update.md

Looks like this minor update was missed before #702 was merged. 👍 
I found the changelog references, and Flux 0.26.0 included Image Reflector Controller v0.16.0 which landed these changes.

Add changelog references to image reflector docs

---

content/en/docs/guides/image-update.md

The examples provided are with bad indentation for the Kustomize patch, generating an reconciliation error when applied like below:
```
$ kustomize build
Error: trouble configuring builtin PatchTransformer with config: `
patch: "- op: add\n path: /spec/template/spec/containers/0/args/-\n value: --aws-autologin-for-ecr
\  "
target:
group: apps
kind: Deployment
name: image-reflector-controller
namespace: flux-system
version: v1
`: unable to parse SM or JSON patch from [- op: add
path: /spec/template/spec/containers/0/args/-
value: --aws-autologin-for-ecr]
```

Fix bad indentation of Kustomize patch examples

---

content/en/docs/guides/flux-e2e.md

Refinements for section 8 on server-side apply.
There does not appear to be a detailed description of server-side apply in the FluxCD documentation, so I've provided links to the Kubernetes documentation on server-side apply.

Refine server-side apply sec 8

---

content/en/docs/guides/image-update.md

At first I just wanted to fix an error in the docs (`image-automation-controller` -> `image-reflector-controller`) but then I also changed some formatting (using actual Kubernetes resource names) and added a hint to simply using the Kubelet identity as opposed to creating a new one.

More detailed native Azure ACR auto-login docs

---

hack/adopters.py

Some logos don't reveal the name of the adopter. Add tooltip to show the
name when hovered.

Add tooltip on the adopters' logos

---

content/en/docs/guides/image-update.md

When migrating from cron-based image registry authentication to native auto login, we ran into a problem where the image-reflector-controller got "UNAUTHORIZED: authentication required" when trying to pull images.
Failing to remove `spec.secretRef` from our `ImageRepository` was causing this issue. 
Solution was found in this Slack thread:
https://cloud-native.slack.com/archives/CLAJ40HV3/p1645436144440909?thread_ts=1644490368.977819&cid=CLAJ40HV3

Add a note about migration from cronjob to native authentication

---

content/en/docs/faq.md

We no longer refer to `kubeval` in our conformance/validation scripts. The `kubeconform` tool is maintained, performs much better according to the copy on their README, and supports (all?) of the same options as it is meant to replace `kubeval`.
* https://github.com/fluxcd/flux2-kustomize-helm-example/pull/54
* https://github.com/fluxcd/flux2-multi-tenancy/pull/64
* https://github.com/fluxcd/kustomize-controller/pull/582

fixup reference to kubeval

---

content/en/ecosystem.md

Reverting 653ce2e67f29600cd9a2ef977979a21f90d8e082 (in the file where ecosystem tools have been moved to), which we can do without worry that people will have their Flux installations impacted poorly at upgrade time, thanks to:
* https://github.com/renovatebot/renovate/pull/14332
ref:
* #740 
* #744

Add renovate to ecosystem tools

---

content/en/blog/2022-03-09-pod-security-standard-restricted.md

Add blog entry about pod security standard 'restricted'

---

content/en/docs/flagger.md
content/en/docs/security/_index.md

Add link to Flagger docs from /docs page

---

content/en/docs/guides/cron-job-image-auth.md

`bash` is not available in docker image and `$(<` doesn't work with `sh`
Fix: #797

Fix comands in ecr-credentials-sync CronJob

---

content/en/docs/cmd/_index.md
content/en/docs/installation.md

It's been archived.
Fixes: #851

Remove GoFish instructions to install 'flux'

---

content/en/blog/2020-12-01-december-update/index.md
content/en/blog/2021-01-06-january-update.md
content/en/blog/2021-02-01-february-update.md
content/en/blog/2021-03-01-march-update/index.md
content/en/blog/2021-03-08-flux-is-a-cncf-incubation-project/index.md
content/en/blog/2021-03-31-april-update.md
content/en/blog/2021-04-29-may-update/index.md
content/en/blog/2021-05-31-june-update/index.md
content/en/blog/2021-07-02-july-update/index.md
content/en/blog/2021-08-02-august-update/index.md
content/en/blog/2021-08-30-september-update/index.md
content/en/blog/2021-10-01-october-update.md
content/en/docs/faq.md
content/en/docs/flux-e2e.md
content/en/docs/guides/image-update.md
content/en/docs/guides/monitoring.md
content/en/docs/migration/flux-v1-migration.md
content/en/docs/migration/helm-operator-migration.md
content/en/docs/use-cases/jenkins.md
content/en/legacy/flux/faq.md
content/en/legacy/helm-operator/helmrelease-guide/automation.md

Fix old toolkit.fluxcd.io links, move most (internal) links to be relative

Fix old toolkit.fluxcd.io links, move most (internal) links to be relative

---

content/en/docs/guides/image-update.md

We support both GCR (legacy) and Google Artifact Registry, the newer alternative
https://cloud.google.com/blog/products/application-development/understanding-artifact-registry-vs-container-registry
Should we include this link in the docs as well, I think it is not needed but maybe could be helpful as a reference too.

Mention Artifact Registry in image update docs

---

content/en/docs/cheatsheets/bootstrap.md
content/en/docs/installation.md

Changes:
- Add Helm repository index caching to bootstrap cheatsheet
- Disable Kustomize remote bases on multi-tenant clusters

Update bootstrap docs

---

Makefile
layouts/partials/hooks/body-end.html
layouts/partials/hooks/head-end.html
layouts/partials/page-meta-links.html

Reverts fluxcd/website#929
Unfortunately the search for tag `legacy` vs `current` does not work.
This is likely a mistake in how our crawler config was transitioned by the Algolia team. I'll reach out and ask if they can help us fix it.
`algoliaOptions` also needs to be changed to `searchParameters` in the new API.

Revert "Update docsy to latest"

---

content/en/ecosystem.md

I'd like to add a link to https://github.com/kluctl/flux-kluctl-controller to the ecosystem page, as discussed in Slack.

Add link to flux-kluctl-controller in ecosystem.md

---

layouts/partials/search-input.html

The last commit broke search. Testing locally I didn't see this coming. Sorry about this.
Once we resolve #931, we can drop this search override.

use old search widget - can be dropped once we merge #931

---

content/en/docs/use-cases/aws-codecommit.md

Based on [AWS official documentation](https://docs.aws.amazon.com/codecommit/latest/userguide/troubleshooting-ssh.html), users should prefix their repository URL with the SSH Key Id registered in the AWS portal.

Add SSH Key ID to AWS CodeCommit

---

content/en/docs/flux-e2e.md

This PR is fixing a typo in the End-to-End documentation.

Fixing typo in E2E documentation

---

content/en/docs/use-cases/gcp-source-repository.md
content/en/legacy/flux/guides/use-gke-workload-identity.md

This pr makes it clear that workload identity isn't always need for GCR access.
Fixes: #966 

Clarify that Workload Identity isn't compulsory

---

content/en/docs/use-cases/gh-actions-helm-promotion.md

Avoid promotion for "Dependencies do not meet ready condition" events.

helm gh actions guide: Exclude events related to dependencies check

---

content/en/docs/use-cases/gh-actions-app-builder.md

When I was reviewing some of the docs I contributed earlier and trying to apply them to a project, I found the "Docker Build" example to be lacking in the existing "Manifest Generation" tutorial. It does what it needs to do for there, which is to briefly cover docker build, but only a side-note and an example of "what we told folks to do back when Flux v1 was widely used."
This doc shows a single GitHub Actions workflow that produces suitable builds for BOTH git tags (ideally tags which are valid semver numbers) AND git branches.
The old example of how to build a latest image only uses the git `SHA` or `REVISION` as a tag name and that's not suitable for Flux anymore (you should use Sortable Image Tags instead) or building images from semver tags. (The example is intentionally this way, …

GitHub Actions App Build guide

---

content/en/docs/cheatsheets/troubleshooting.md

Follow-up to cover common likely issue noticed while attempting to debug a red-herring issue uncovered in:
* fluxcd/source-controller#831
When users have installed on a k3s cluster, sometimes they don't ask for Helm controller but k3s still installs these CRDs:
```
addons.k3s.cattle.io                             2022-07-11T18:18:17Z
helmchartconfigs.helm.cattle.io                  2022-07-11T18:18:17Z
helmcharts.helm.cattle.io                        2022-07-11T18:18:17Z
```
This seems like the best place in our docs to highlight that `helmcharts` CRD is known to sometimes conflict with other CRDs called `helmcharts` – I suspect Rancher will be unreceptive to force their users to opt into these CRDs and adjust every doc that expects them to come pre-installed on k3s, so a mention in our …

Add troubleshooting note for k3s HelmChart

---

content/en/docs/security/best-practices.md

The only controller that supports auto decryption is Kustomize. This removes the inaccurate reference to Helm on this context.
An additional commit resolves presentation issues due to the `details` block with was making the Markdown to be interpreted as HTML. Here's the before/after:

Fix Secret Decryption

---

content/en/docs/security/best-practices.md

It's not easy to validate a CNI plugin's implementation of
NetworkPolicies and cyclonus is used by the Kubernetes folks:
https://kubernetes.io/blog/2021/04/20/defining-networkpolicy-conformance-cni-providers/

Mention Cyclonus for NetworkPolicy validation

---

content/en/docs/cheatsheets/bootstrap.md

Tested SOCKS5 support using two separate server implementations:
- https://github.com/ring04h/s5.go
- https://github.com/MisterDaneel/pysoxy

Add SOCKS5 ssh proxy for git docs

---

content/en/docs/cheatsheets/oci-artifacts.md

Missing `spec.prune` causes example to fail to reconcile:
```
Kustomization reconciliation failed: Kustomization/oci/podinfo dry-run failed, reason: Invalid, error: Kustomization.kustomize.toolkit.fluxcd.io "podinfo" is invalid: spec.prune: Required value
```
Signed-off-by: David Harris <david.harris@weave.works>

doc: missing parameter in example

---

MAINTAINERS

Per discussion in slack, @alisondy is inactive.
(Is this the correct way to remove an inactive maintainer? I went through some history and didn't find any prior instances where we had removed someone. Way back in Flux v1 history, I found that we had a sort of "Emeritus" or retired maintainer status. Are we still doing that?)
I know we are parsing these files now, so I did not want to mess with the structure at all in case it would cause problems.
Linked with:
* https://github.com/fluxcd/community/pull/232

Remove @alisondy (inactive)

---

content/en/resources.md

Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>
This PR resolves [issue #953](https://github.com/fluxcd/website/issues/953#issue-1244722958) by adding GitOpsCon 2022 video playlist to the Resources section.

Adding GitOpsCon videos to resources section

---

content/en/flux/flux-e2e.md

The Kustomize Controller's reconciling can take up to 3x `spec.timeout`
(This was an action item from today's Flux Dev meeting)
It seemed to fit naturally in this short paragraph about the Kustomize Server-Side Aply timeout that was missing details. Is there anywhere else we can highlight this, perhaps in the Kustomize controller docs as well

Add detail about Kustomize controller timeout

---

content/en/flux/guides/repository-structure.md

Currently, the examples in the [Ways of structuring your repositories](https://fluxcd.io/docs/guides/repository-structure/) section are broken. 
The Kubernetes manifests are missing an `apiVersion` property which means they'll fail when applying.
This PR adds the missing properties to every example on that page.

Add missing `apiVersion` fields to examples in the Repository Structure page

---

content/en/flux/gitops-toolkit/source-watcher.md

Addresses the second task in https://github.com/fluxcd/website/issues/640
- Remove deprecated io/outil function calls
- Update documented Reconcile function with minor changes

Update source-watcher.md with minor changes

---

content/en/legacy/helm-operator/get-started/using-helm.md
hack/update-helm-op.sh

This changed unrelated docs in
https://github.com/fluxcd/website/commit/34c756a6#diff-1df7f48852efaabb59a1fbc8c75a2f7a44b1eed0cece86e53835b364d6c74b0cR99

helm-op update script: read versions properly

---

content/en/flux/guides/helmreleases.md

One more additional guide for HelmReleases with values that come from a SOPS encrypted secret.
There are a few things to be aware of that make this not quite straightforward extrapolation from the ConfigMapGenerator example, I think this should be good to help more users from struggling. This has come up several times in Slack, we finally had a user who was persistent enough to discover all of the major tripping hazards and help me document them here.
We may want to let this one gather some reviews before it merges, I have tested it before writing, so strictly speaking this doc is not yet "tested" as in shown to work from a reading of the document, but the methods are tested and verified to work.
Thanks to our Slack community for helping us cover all our bases in the docs! 🌮 🎉

HelmRelease Guide: Values Secret generated with Kustomize and SOPS

---

content/en/flux/cheatsheets/oci-artifacts.md

Add Cosign signing and Flux verification to the OCI artifacts guide.
Part of: https://github.com/fluxcd/flux2/issues/3155
⚠️ To be merged after Flux v0.35 release!

Add Cosign signing and verification to OCI docs

---

content/en/_index.html

As Flux Legacy and Helm Operator will be archived Nov 1, we might want to remove them from the landing page and simplify our messaging already.

remove Flux Legacy from landing page

---

content/en/flux/guides/helmreleases.md

This turned out to be the number of backslash escapes needed to get this example to work as a primary source
The error I received without this change from SOPS CLI was: malformed yaml on line 4

fix helmrelease guide example .sops.yaml file

---

content/en/ecosystem/index.md

Adds a new tool https://github.com/raffis/gitops-zombies to the tools list.
I quickly created a simple tool to identify workload which is not managed by GitOps. 
Quite useful on clusters which are getting migrated to gitops or where pruning is disabled, maybe this helps somebody.

add raffis/gitops-zombies to the tools list

---

assets/scss/blocks/_cncf.scss
layouts/shortcodes/blocks/cncf.html

Ref: https://github.com/fluxcd/flux2/issues/3212

add LF trademarks bit in footer

---

.github/dependabot.yml
.gitignore
.stignore
Makefile
README.md
assets/scss/main.scss
config.yaml
content/en/flux/migration/helm-operator-migration.md
go.mod
go.sum
netlify.toml
okteto.yml

Move to docsy as Hugo module

---

content/en/flux/faq.md

Encourage users to adopt Flux OCI distribution model and move away from Kustomize remote bases.

FAQ: Should I be using Kustomize remote bases?

---

content/en/ecosystem/index.md

removed "/product" from the url. It was giving 404 at weave.works website. 
Signed-off-by: Mohamed F. Ahmed <MohamedFAhmed@users.noreply.github.com>

Fix URL for Weave Gitops Enterprise

---

content/en/flux/installation.md

Add `target-namespace` to fix error message from `flux get kustomizations`:
> _Service/podinfo namespace not specified, error: the server could not find the requested resource_
Signed-off-by: Piotr Sobieszczański <piotr.sobieszczanski@gmail.com>

Update Dev install -> create kustomization from CLI

---

content/en/roadmap.md

Changes:
- Reshape the roadmap into milestones based on Flux feature sets
- Add GA milestones and current focus
- Set deadline for the first GA milestone
- List all RFCs and their status
Preview: https://deploy-preview-1247--fluxcd.netlify.app/roadmap/

Add feature-based milestones to roadmap

---

assets/scss/blocks/_blog.scss
layouts/docs/baseof.html
layouts/partials/graduation.html

Towards EOY it might make sense to remove the highlight in our docs that informs users of Flux's graduation. It takes up quite a bit of screen-space on mobile, etc. Hopefully everyone learned about the news by the end of the year. :-)

docs: remove graduation highlight

---

content/en/flux/components/helm/options.md
content/en/flux/components/source/options.md

This PR depends on this one: https://github.com/fluxcd/source-controller/pull/989
Reference issue: https://github.com/fluxcd/flux2/issues/3426
Also: Added the --feature-gates flag to the helm controller docs from #1316

Document CacheSecretsAndConfigMaps feature flag in source-controller

---

content/en/flux/components/image/options.md

Auto-login flag options are deprecated from image-reflector-controller with the v1beta2 API.

Remove image reflector deprecated options

---

content/en/flux/cheatsheets/bootstrap.md
content/en/flux/cheatsheets/oci-artifacts.md
content/en/flux/gitops-toolkit/packages.md
content/en/flux/guides/cron-job-image-auth.md
content/en/flux/guides/image-update.md
content/en/flux/guides/sortable-image-tags.md
content/en/flux/migration/flux-v1-automation-migration.md
hack/import-flux2-assets.sh

- Update the mention of old API version.
- Add example of the latest ten tags in the scan result.
- Remove section about authentication with old autologin flags and add
reference to the spec docs provider section.
- Add ImagePolicy examples section that are no longer in the spec docs.
- Update link to native auth docs and remove empty section about GCP
native auto-login.

image-reflector-controller v1beta2 updates

---

content/en/flux/cheatsheets/bootstrap.md

Hi
While configuring tf-controller to send notifications to fluxcd, I've followed the current instructions in [enable-notifications-for-third-party-controllers](https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers) but continuously got an error and Terraform-CRD notifications did not worked.
I've investigated and with these proposed changes to the patch, the notifications worked again, as intended. 
It could be good to add these to the instructions in [enable-notifications-for-third-party-controllers](https://fluxcd.io/flux/cheatsheets/bootstrap/#enable-notifications-for-third-party-controllers) to help future users
I've used recent versions of fluxcd and tf-controller:   
- tf-controller v0.13.1
- fluxcd v0.39.0
Keep up the great work - cheers

bugfix patch for notifications fluxcd v0.39.0 tf-controller v0.13.1

---

content/en/flux/cheatsheets/oci-artifacts.md

The old link has been deprecated and points to this new one.
Signed-off-by: Max Jonas Werner <max@e13.dev>

fix link to keyless signatures docs

---

content/en/flux/guides/notifications.md

Just a little typo `heath` -> `health`

Fix typo in notifications.md

---

content/en/flux/guides/cron-job-image-auth.md

FIxed `encypted` -> `encrypted`

fix typo in documentation

---

content/en/flux/installation.md

This change documents the possibility to use a deploy token instead of a personal access token or an SSH deploy key.
This feature is implemented with:
* https://github.com/fluxcd/flux2/pull/3654
and was discussed in:
* https://github.com/fluxcd/flux2/discussions/3595
/cc @makkes

Add documentation for new `--deploy-token-auth` option

---

content/en/roadmap.md

Ref: https://github.com/fluxcd/terraform-provider-flux/issues/426

Add Terraform Provider to GA roadmap

---

content/en/flux/installation.md

We changed the default algorithm to ECDSA in fluxcd/flux2#2041.

fix note on default key algorithm for bootstrap

---

hack/import-flux2-assets.sh

We changed the directory structure of the specs in the respective controllers' v1 versions. Until a full Flux release has been cut we need to exclude all v1 versions from being imported until #1427 has landed.

exclude v1 from API spec imports

---

content/en/flux/use-cases/openshift.md

On macOS with Zsh the OpenShift instructions fail to execute correctly:
Expected:
```
NS="flux-system"                                                                                                                
oc adm policy add-scc-to-user nonroot system:serviceaccount:$NS:kustomize-controller
oc adm policy add-scc-to-user nonroot system:serviceaccount:$NS:helm-controller
oc adm policy add-scc-to-user nonroot system:serviceaccount:$NS:source-controller
oc adm policy add-scc-to-user nonroot system:serviceaccount:$NS:notification-controller
oc adm policy add-scc-to-user nonroot system:serviceaccount:$NS:image-automation-controller
oc adm policy add-scc-to-user nonroot system:serviceaccount:$NS:image-reflector-controller
```
Output:
``` …
```

Doc OpenShift fix variable substitution $NS->${NS}

---

content/en/flux/cheatsheets/bootstrap.md
content/en/flux/cheatsheets/sharding.md

Add controller sharding cheatsheet.
Preview: https://deploy-preview-1444--fluxcd.netlify.app/flux/cheatsheets/sharding/

docs: Controller sharding and horizontal scaling

---

content/en/flagger/install/flagger-install-on-google-cloud.md
content/en/flagger/tutorials/kubernetes-blue-green.md
content/en/flagger/usage/alerting.md
content/en/flux/guides/notifications.md
content/en/flux/migration/flux-v1-migration.md

This PR changes the suggested Slack channel from "general' to hopefully prevent users that blindly copypasta like myself from alerting their entire company :sweat_smile:.
TIL Slack webhook URLs are not solely scoped to the channels they are created with and can be overridden.

Prevent future embarrassment by changing Slack channel example

---

content/en/flux/installation.md

Part of: https://github.com/fluxcd/flux2/issues/3735

Use flux_bootstrap_git in Terraform docs

---

content/en/flux/guides/helmreleases.md

Match the file name that appears in the error with the example.

File name mismatch between the error and example's spec

---

content/en/flux/security/_index.md

Cosign v2 comes with breaking changes to the verify command, this PR updates the verify instructions with the required flags.

Update verify instructions to cosign v2

---

content/en/flux/guides/sortable-image-tags.md
content/en/flux/use-cases/gh-actions-app-builder.md
content/en/flux/use-cases/gh-actions-auto-pr.md
content/en/flux/use-cases/gh-actions-helm-promotion.md
content/en/flux/use-cases/gh-actions-manifest-generation.md

Primary purpose is to update the GH Actions syntax in preparation for the [deprecation of `set-output`](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), in order to keep the examples functional in the future.
In addition to that, I made some straightforward updates for the well-known GH Actions used in the examples like `docker/login-action`, `docker/setup-*` and `actions/checkout`.

Update GitHub Actions examples syntax + actions versions

---

content/en/flux/use-cases/openshift.md

OpenShift since 4.11 adds the same pod-security labels to the `flux-system` Namespace as flux defines, but with other values.
This triggers endless reconciliations.
This reconciliation can be avoided by *removing* the label specifications from flux - with a patch to the `Kustomization` object.
This PR documents how this can be done.
Example
```
kustomization/flux-system.flux-system
Namespace/flux-system configured
```
Fix: https://github.com/fluxcd/flux2/issues/3995

openshift: Explain how to remove the pod-security labels

---

MAINTAINERS

@hiddeco @stefanprodan @scottrigby 
I volunteer as a maintainer for fluxcd/website
I reviewed the maintainer [community roles doc](https://github.com/fluxcd/community/blob/main/community-roles.md#maintainer) which is quite familiar to me now, and it looks like I meet all of the criteria.
For easy reference, my history as a contributor here:
* PRs I contributed: https://github.com/fluxcd/website/issues?q=author%3Akingdonb
* Issues where I was involved: https://github.com/fluxcd/website/issues?q=is%3Aopen+mentions%3A%40me
I am also currently a maintainer in the `community` and was also maintainer on the `fluxcd/flux` repo that got archived.
Adding this will be a big help, so I can review and merge PRs from @mehak151 as we begin to get rolling on the GSoD work ✅

Add @kingdonb to maintainers

---

content/en/flux/use-cases/gh-actions-helm-promotion.md

This PR uses the latest additions to the Alert API to better filter events and send rich metadata to the GitHub runner.
Changes:
- use `eventMetadata` to set the environment name, cluster name, region
- use `inclusionList` to trigger the promotion on upgrades
- explain how to trigger the promotion only after tests have been successfully run

Enhance the Helm promotion workflow

---

content/en/flux/migration/_index.md

Addressing a part of this feedback by @dholbach: https://github.com/fluxcd/website/issues/718

Rename 'Migrate' to 'Migrate from Flux v1'

---

content/en/flux/flux-e2e.md
content/en/flux/use-cases/gh-actions-app-builder.md
content/en/flux/use-cases/gh-actions-auto-pr.md
content/en/flux/use-cases/gh-actions-manifest-generation.md
content/en/flux/use-cases/jenkins.md
content/en/flux/use-cases/karmada.md

If anyone thinks that one of these does not need any updates, then we can remove it from this list pre-emptively.
I added a notice to each doc that I haven't personally reviewed recently, (regardless of whether I am the original author. Trying to use a broad stroke to get as much done as possible.)
The use-cases docs that are not covered here are all ones intended to be migrated into the Installation guides, per the GSoD plan that is being advanced here. So the use-cases section of the docs may go away entirely, (unless some of these docs turn out to survive all this without getting relocated):
https://github.com/fluxcd/website/issues/1560

Mark some use-cases docs stale

---

hack/import-flux2-assets.sh

`sort -V` doesn't properly sort according to semver. This led to an old version of NC (1.0.0-rc.4) being pulled instead of the latest 1.0.0.

Fix ordering of versions when pulling component docs

---

content/en/flux/use-cases/gh-actions-helm-promotion.md

Fixed the regex shown in the example for the Alert/Notification used to trigger an helm release promotion GitHub workflow.
The example that was there give the following error:
> error parsing regexp: missing argument to repetition operator: *

fix regex example in flux notification for helm release promotion

---

content/en/flux/cheatsheets/sharding.md

This commit updates the docs to use `DoesNotExist` operator (`!`)
for sharding selector.
The current docs use `NotIn` (`notin`) operator, which means that each
time a new shard is added, the root flux deployments needs to be updated
to exclude the new shard label. By using `DoesNotExist` operator, the
root flux deployments can remain unchanged when a new shard is added.
This makes it slightly easier to add and remove shards.

docs: Use DoesNotExist operator in shard selector

---

Makefile
layouts/partials/hooks/head-end.html

We don't want archived docs for old Flux versions to be indexed by search engines so that all pages at https://v2-0.docs.fluxcd.io don't turn up in search results.
All Netlify branch builds now lead to all pages being built and deployed to have the `noindex` directive in the page's header.
This PR can be merged immediately as it has no effect on how the site is build and deployed right now. It will only have an effect as soon as we start publishing branch builds for older Flux versions.
I will update the `v2-0` branch from `main` as soon as this PR is merged for the changes to take effect for that branch's deployment.

Prevent robots from indexing branch builds

---

hugo.yaml
layouts/partials/navbar-version-selector.html
layouts/partials/navbar.html
layouts/partials/version-banner.html

I took the partial that's part of this change from the Docsy sources and slightly modified it to have the "deprecation-warning" class and some additional text. The original can be found here: https://github.com/google/docsy/blob/3f3172a190ac9b24aa5b9c695f62c3fee8273ac2/layouts/partials/version-banner.html
This commit also moves the link to Flagger into the top navbar so that we can actually use the version drop-down for listing Flux versions. A dedicated "Documentation" link in the top navbar now directs users to the Flux documentation.
Parts of this change will have to be forward-ported to `main` once 2.1 has been released. I'll create a PR for this later.

Add version dropdown and deprecation notice

---

.gitignore
Makefile
hack/import-flux2-assets.sh

Since the website will be built for the 2.0.x minor release, the import script needs to fetch the API docs for the controller versions of the latest 2.0.x Flux release. This change makes the script aware of the desired version (derived from the `BRANCH` environment variable that is set by Netlify).
This change is a subset of the changes implemented in #1577. We cannot simply backport 1577 since the changes in there required some changes to the controller API docs which haven't been released as part of a Flux 2.0.x release, yet.

Make import-flux2-assets.sh aware of the desired Flux version

---

content/en/flux/monitoring/custom-metrics.md

This documents how kube-state-metrics can be used to configure custom flux metrics.
The guide has references to the configurations in https://github.com/fluxcd/flux2-monitoring-example that exist in https://github.com/fluxcd/flux2-monitoring-example/pull/1.
Preview: https://deploy-preview-1610--fluxcd.netlify.app/flux/monitoring/custom-metrics/

Add custom metrics guide

---

content/en/flux/monitoring/custom-metrics.md
content/en/flux/monitoring/events.md
content/en/flux/monitoring/logs.md
content/en/flux/monitoring/metrics.md

- Add new metrics, logs and events docs.
- Update custom metrics docs based on the new example configuration.

New Metrics, Logs and Events docs

---

content/en/flux/security/_index.md

This has come up many times on Slack and GitHub so I'm creating this section we can link to in the future.

Add section about Flux's cross-namespace policy

---

content/en/flux/flux-gh-action.md

Add missing `--output=json` flag.

Fix GHA cosign example

---

content/en/flux/components/helm/options.md
content/en/flux/components/image/options.md
content/en/flux/components/kustomize/options.md
content/en/flux/components/notification/options.md
content/en/flux/components/source/options.md

The re-organization that happened as part of https://github.com/fluxcd/website/pull/1573 removed this page.
PR https://github.com/fluxcd/website/pull/1573 added a redirect for /flux/cheatsheets/bootstrap but in this case it's better to specifically link directly to the customization guide instead of the general configuration page.
closes https://github.com/fluxcd/website/issues/1658

Fix link to bootstrap customization guide

---

content/en/flux/installation/upgrade.md

Add example on how to upgrade when the Flux image automation feature has been enabled at bootstrap.
Closes: https://github.com/fluxcd/flux2/issues/4259

Add a note for image automation to upgrade guide

---

.github/workflows/backport.yaml
.github/workflows/build-push-hugo-image.yml
.github/workflows/sync-labels.yaml
.github/workflows/update-contributors.yaml

Automated backport to v2-0, triggered by a label in https://github.com/fluxcd/website/pull/1670.
I had to manually create this PR because of an issue with permissions of the bot token.

[v2-0] Bump actions/checkout from 4.0.0 to 4.1.0

---

layouts/shortcodes/home/next_event.html

Fix #1671
There is a fully-formed link in the `.where` of each calendar event in the generated yaml, but hugo sanitizes it.
We were expecting a bare URL here anyway, instead of a link. Rework the shortcode slightly so it behaves.

Add safeURL to fix "next event" partial

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1673

update hugo to v0.119.0

---

netlify.toml

Automated backport to v2-0, triggered by a label in #1675.
I had to manually create this PR because of a conflict in the file.

[v2-0] update hugo to v0.119.0

---

content/en/flux/faq.md

Add alternative procedure to `How can I safely move resources from one dir to another?`

FAQ: Explain how to use the `prune` annotation when moving resources

---

content/en/flux/installation/bootstrap/generic-git-server.md

changed "exiting" to "existing"

fix typo in generic-git-server.md

---

content/en/flux/gitops-toolkit/debugging.md

The old link to guides/monitoring.md is not working. The new one links to the prometheus metrics.

Fix monitoring link on debugging.md

---

content/en/flux/concepts.md

- Added a link to GitOps Principles, fix: https://github.com/fluxcd/website/issues/493
- Added definition for gotk as per https://cloud-native.slack.com/archives/CLAJ40HV3/p1690994781510689

Update Core Concepts

---

content/en/flux/guides/cron-job-image-auth.md
content/en/flux/guides/mozilla-sops.md
content/en/flux/guides/repository-structure.md

Hi @stefanprodan @hiddeco!
I am addressing this PR #1545
> **NOTE:** I've tested everything on my side using `kustomize build` command
There is a point I'd like to discuss. In `cron-job-image-auth.md` we were using `patchesStrategicMerge` that allows us to apply patches to multiple resources within one patch file. When I tried to do the same with inline patches, I wasn't able because it's not supported in Kustomize version earlier than 5.2.1. Please check the [changelog file](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.2.1) for a [PR](https://github.com/kubernetes-sigs/kustomize/pull/5194) that adds a support for this. When I upgrade to the latest version I was able to do it.
So I'd like to clarify if the latest version of FluxCD supports the latest stable …

docs: replace `patchesStrategicMerge` with `patches`

---

data/adopters/2-flagger.yaml

Tchibo wants to provide its developers progressive delivery tooling for its internal developer platform. As Flux is already in use, Flagger perfectly complements the GitOps approach here.
An example application implementation, which covers several use cases, got already provided for internal usage for our developers.

Add Tchibo to flagger adopters

---

content/en/flux/security/_index.md

Small update to the cosign verify command.
- ensure the image is produced by https://github.com/fluxcd and not https://github.com/fluxcd-something-else
- escape the wildcard dot in the domain name. It's unlikely to be an issue but it's a bit safer by default when validating hostnames with a regexp.

Update cosign verify certificate identity regexp

---

content/en/roadmap.md

We decided to ship **HelmRelease** `v2beta2` instead of `v1` this year and delay GA until Q1 2024 to gather feedback on the helm-controller refactoring.

Update Helm GA roadmap

---

content/en/flux/installation/configuration/vertical-scaling.md

Recommend using tmpfs based on benchmark results from https://github.com/stefanprodan/flux-benchmark 
Part of: https://github.com/fluxcd/flux2/issues/4410

Add in-memory kustomize builds advice to scaling docs

---

content/en/flux/installation/bootstrap/gitlab.md

A template name in the GitLab documentation read `export GITLAB_TOKEN=<gh-token>` when the intent was probably for it to read `export GITLAB_TOKEN=<gl-token>`

Fix typo in GitLab documentation

---

.github/workflows/update-contributors.yaml

Manual backport to v2-0 due to failure in automatic backporting of #1737.

[v2-0] Bump actions/setup-python from 4 to 5

---

hugo.yaml

Following the procedure documented in
https://fluxcd.io/flux/releases/procedure/#distribution-minor-release-website.
main branch update in #1741

Prepare release of Flux 2.2 - v2.1 archive

---

content/en/flagger/install/flagger-install-with-flux.md
content/en/flux/cheatsheets/oci-artifacts.md
content/en/flux/cheatsheets/troubleshooting.md
content/en/flux/faq.md
content/en/flux/flux-e2e.md
content/en/flux/gitops-toolkit/packages.md
content/en/flux/guides/helmreleases.md
content/en/flux/guides/image-update.md
content/en/flux/guides/repository-structure.md
content/en/flux/guides/sealed-secrets.md
content/en/flux/installation/configuration/sharding.md
content/en/flux/migration/helm-operator-migration.md
content/en/flux/monitoring/alerts.md
content/en/flux/monitoring/custom-metrics.md
content/en/flux/use-cases/gh-actions-helm-promotion.md
content/en/flux/use-cases/helm.md
content/en/flux/use-cases/karmada.md

Notification-controller is introducing v1beta3 APIs for Alerts and Providers, refer https://github.com/fluxcd/notification-controller/pull/540. Helm-controller is introducing v2beta2 API for HelmRelease. Update all the references to those APIs to use the new version.
Depends on https://github.com/fluxcd/notification-controller/pull/540 and https://github.com/fluxcd/helm-controller/pull/738.

Update HelmRelease, Alerts and Providers to Flux v2.2.0

---

content/en/flux/components/kustomize/options.md

Changes for Flux 2.2.0:
- Add the `--override-manager` flag
- Update the `DisableStatusPollerCache` feature gate default value
Part of: https://github.com/fluxcd/flux2/issues/4410

Update kustomize-controller options

---

content/en/blog/2023-12-12-announcing-flux-v2.2.0/index.md

Supersedes: #1733
Part of: https://github.com/fluxcd/flux2/issues/4410
:eyes: **Preview:** https://deploy-preview-1744--fluxcd.netlify.app/blog/2023/12/flux-v2.2.0/

Flux v2.2.0 release blog

---

content/en/flux/installation/bootstrap/gitea.md

This PR introduces a page that provides guidance specific to Gitea. 
Related to: https://github.com/fluxcd/flux2/pull/4270 bootstrap gitea command

feat: Add Flux bootstrap for Gitea

---

content/en/flux/installation/_index.md

Followup: https://github.com/fluxcd/flux2/pull/4484

Add Kubernetes 1.29 to supported versions

---

.github/labels.yaml

This is in preparation of using the v2-2 branch for the production website fluxcd.io instead of main.

Add 2.2 backport label

---

content/en/roadmap.md

Fix fluxcd/community#322 - there is a spelling error in the roadmap doc, s/Cosgin/Cosign/

Fix spelling error in roadmap.md

---

assets/scss/_index.scss
data/resources.yaml
hugo.yaml
layouts/index.searchindex.json
layouts/partials/filter-panel.html
layouts/partials/hooks/body-end.html
layouts/partials/resource.html
layouts/partials/template-container.html
layouts/partials/template-resource.html
layouts/resources/list.html

Rebased from:
* #1693 
To address the Flux request for CNCF tech docs team, in https://github.com/cncf/techdocs/issues/192
Thank you @thisisobate!

Resource page update to include external articles/blogs

---

Makefile
hugo.yaml
netlify.toml

https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120
While cruising the logs I noticed a deprecation warning that can be fixed

Fix Hugo 0.112.0 deprecation

---

.github/workflows/netlify.yml

Resolves #1787
We will still need to make further changes, once a new minor version is released, or before then, so that this script does not need to change every minor release. It will be easy to make this script self-updating, but someone will still need to create the new build hook variable with Netlify and copy it to the secret, so, at least we can make it one less step.
One other issue is that when this ever fails, there is no notification back on the Actions dashboard. The curl POST calls are asynchronous and they don't return any status here.
Let's merge this and keep it simple, there's no much sense writing a script any more complicated than this one when we can't quite script the whole thing.

Change netlify 6-hourly job to update current release

---

content/en/_index.html
content/en/ecosystem/index.md
content/en/support.md

This article is from 8 months ago, Flux has had two minor releases since GA. Preserve the banner in an HTML comment so we don't forget how this was done, in case we need to announce something again later.
FWIW, also some links to "August 2 webinar" on that page are no longer good, as weave.works has gone down for the count:
https://go.weave.works/Webinar-FluxCD-Positioned-for-Growth_LP.html

Update header banner to 2.2 release blog

---

data/adopters/1-flux-v2.yaml

Noticed the logo isn't showing up in Adopters, it isn't because of any reason except for mismatched filename.
I have checked that SVG logos are OK here and it appears they are. (@kvaps FYI thanks for adding this here!)

Fix aenix logo in adopters

---

assets/scss/_kubecon.scss
assets/scss/main.scss
external-sources/fluxcd/community
hugo.yaml

The deploy preview is ready at:
https://deploy-preview-1804--fluxcd.netlify.app/kubecon/
How this is supposed to work, you can just edit the Google Sites page, and this workflow in:
* fluxcd/community#349
...comes along every 6 hours, wget's the html and feeds it through `html2md`, a Go tool that does a good job of converting HTML into Markdown
Then it runs a bunch of string substitutions on the Markdown output, to make sure we can serve the images from fluxcd.io instead of hot-linking Google Sites. The images all have some semantic associations that are conveyed through alt tags. We can change anything here, but I think it's pretty good for a first pass, and it should only open a Pull Request when there is a substantive change on the Sites.
Then, further string substitutions ensure that …

Add Kubecon page for KubeCon Paris 2024

---

.github/workflows/netlify.yml

Following the example in:
https://medium.com/hostspaceng/triggering-workflows-in-another-repository-with-github-actions-4f581f8e0ceb#:~:text=Set%20Up%20the%20Trigger%20Workflow,for%20triggering%20the%20target%20workflow.
This exposes the Netlify job as a repository_dispatch, which allows it to be triggered from fluxcd/community.
Some additional configuration may be needed in the `BOT_GITHUB_TOKEN` for fluxcd/community.
See also:
* https://github.com/fluxcd/community/pull/365

Add repository_dispatch to trigger a website rebuild from fluxcd/community

---

content/en/flux/guides/image-update.md

Add example on how to select the latest version by extracting the semver from tags in the format `<semver>-<distro>`
e.g. [Redis on DockerHub](https://hub.docker.com/_/redis).

Add image policy example for DockerHub format

---

content/en/flux/get-started.md
content/en/flux/installation/bootstrap/github.md

Fix: https://github.com/fluxcd/flux2/issues/4412
Fix: https://github.com/fluxcd/flux2/issues/2329
Supersedes: #1722 
PS. These settings were tests on https://github.com/controlplaneio-fluxcd/d1-fleet

Add GitHub fine-grained PAT permission to bootstrap docs

---

content/en/flux/installation/configuration/sharding.md

The ResourceQuota resource should not be duplicated by the sharding kustomize overlay.

Remove ResourceQuota from sharding overlay example

---

data/resources.yaml

The first article we have reblogged has unfortunately gone 404

Remove article - broken link

---

content/en/flux/use-cases/helm.md

If applied, this commit will correct a typo.

docs: Fix typo in documentation

---

hugo.yaml

The menu entry is removed by this PR, but the URL `fluxcd.io/kubecon` stays valid and intact. Filing this as a piece of the puzzle in response to @stefanprodan's request. It is a good idea to keep the link perpetually valid, as people may still have the QR code, we can update it to point at later versions though.
I think later we still would make two further adjustments, at some future date (not before we merge this):
1. Move the KubeCon Paris markdown file to some historical place here in the `fluxcd/website` repository
2. Then in the (further) future, when we are preparing for next KubeCon, we can re-enable `/kubecon` as an external source - put back exactly like 78c7e102684fa44f4231744096c3f31e65660e1e (#1804)
We don't have to do Google Sites if we don't want, we could use any markdown …

Hide the KubeCon Paris menu entry

---

data/resources.yaml

I was looking for this one - let's post it first.
If there are any others mention them here and I'll add them before it merges. I think if anyone publishes a Flux-centric KubeCon Recap post, we could also cross-link it on the Flux website using our new remote resources feature

Add Flux BoF video to resources

---

hack/import-calendar.py

Fix issue introduced in #1891 
(the issue: the team calendar's sort order is now out of whack)
There was some implicit sorting and some re-sorting, it's probably clearer if we pass the original timestamp through to the "formatted_event" and sort by that field (even though it is not used directly for display)

add timestamp to fix calendar sort

---

hack/import-calendar.py

When the ICS file contains an organizer, the script failed because it didn't parse the field correctly.

Fix parsing calendar with organizer

---

hack/import-calendar.py

The existing URL started returning 404s so I changed it to the one that it was apparently replaced with.
For posterity, you go to https://lists.cncf.io/g/cncf-flux-dev/calendar, scroll down, click on "Subscribe to Calendar" and copy the URL from the subsequent dialog.

Fix calendar import

---

Dockerfile
content/en/.gitignore
go.mod
hugo.yaml

I have narrowed down the issues upgrading hugo to a docsy v0.7.0 release breaking change that brings Bootstrap 5.
I don't know the exact nature of the errors I get with those upgrades, but the good news is it looks like Hugo upstream is already using Go 1.21, so we should at least upgrade to that version to match.
I will investigate the Bootstrap 5 upgrade situation further and get back to us soon about it. In the mean time, I've done loads of testing with `make production-build URL=https://fluxcd.io` on different versions of go modules and go compilers, to determine that this combination works, and we do not have to stay on Go 1.19 any longer.
(Doing one more test locally, since I do not think there is any CI workflow other than the hugo-support image builder that will trigger, and that …

Upgrade go to 1.21, clean up build issues

---

content/en/flux/installation/_index.md

Fix two minor typos on https://fluxcd.io/flux/installation/.

Fix minor typos in Flux installation doc

---

hack/import-calendar.py

Do not put events at the top of the calendar that started more than 1 hour ago
Today at 10:00 AM Eastern (GMT-4), April 17, the event from 16 hours ago Australia Edition finally dropped out of the list. That event was at 8:00 AM UTC+10 and it stayed in the list until the end of the day April 17, Brisbane time.
A bit not sure about why this happens, whether it's our code or the recurring ical events module that continues to include these events. It doesn't really matter if it's two minutes ago or an hour ago, up to 24 hours ago is too long, and I wanted to avoid "the event is actually starting now and the refresh job just ran, so it just dropped off the calendar, right as people are meant to be finding the link to join there." An hour seems like just long enough. The website only refreshes …

Fix calendar timing - stale events hang around too long

---

content/en/roadmap.md

Changes:
- mark as completed some of the tasks for Q2
- add terraform provider improvements to Q2 milestone
- move AWS conformance tests to Q3 milestone

Update the roadmap for Q2/Q3

---

content/en/flux/installation/bootstrap/azure-devops.md
content/en/flux/installation/bootstrap/generic-git-server.md

Fix: https://github.com/fluxcd/flux2/issues/4726
DevOps doc preview: https://deploy-preview-1936--fluxcd.netlify.app/flux/installation/bootstrap/azure-devops/

Update Azure DevOps docs with RSA SHA-2 keys

---

content/en/flux/guides/mozilla-sops.md

AAD Pod identity is deprecated in favor of workload identity. This PR 
- Adds documentation to use Azure workload identity to encrypt secrets using mozilla sops.
- Removes references to aad pod identity.

Update SOPS documentation for Azure to use workload identity

---

assets/js/calendar.js
assets/scss/blocks/_blocks.scss
assets/scss/blocks/_calendar_dark.scss
content/en/_index.html
layouts/shortcodes/home/calendar.html
layouts/shortcodes/home/calendar_dark.html

NOTE: Before this merges:
until fluxcd/community#396 merges
Check out the Deploy Preview here: https://deploy-preview-1940--fluxcd.netlify.app/
(note changes:
* Our Team Calendar: https://deploy-preview-1940--fluxcd.netlify.app/#calendar
* Community: https://deploy-preview-1940--fluxcd.netlify.app/community/#getting-involved)
These are the changes we discussed at the Flux Dev Meeting yesterday.
PR notes:
Let's reduce the amount of text and noise on the landing page, we only need to show the first few events.
In order to use the shortcode for the calendar in the external-imports, we need to avoid having parts of its HTML content converted into `<pre>` sections by the hugo builder.
It's an annoying change, but this is the only external-import with any shortcode that I'm aware of, and …

Move some of calendar to community.md page

---

content/en/flux/cheatsheets/oci-artifacts.md
content/en/flux/gitops-toolkit/packages.md
content/en/flux/guides/image-update.md
content/en/flux/migration/flux-v1-automation-migration.md

Depends on https://github.com/fluxcd/image-automation-controller/pull/647, to be release as part of Flux v2.3 release.
- Update all the references of v1beta1 API to v1beta2
- Update the outputs and template examples to use the new results

Update ImageUpdateAutomation to v1beta2 API

---

content/en/flagger/install/flagger-install-with-flux.md
content/en/flux/cheatsheets/oci-artifacts.md
content/en/flux/cheatsheets/troubleshooting.md
content/en/flux/faq.md
content/en/flux/flux-e2e.md
content/en/flux/guides/helmreleases.md
content/en/flux/guides/image-update.md
content/en/flux/guides/repository-structure.md
content/en/flux/guides/sealed-secrets.md
content/en/flux/installation/configuration/sharding.md
content/en/flux/migration/helm-operator-migration.md
content/en/flux/use-cases/gh-actions-helm-promotion.md
content/en/flux/use-cases/helm.md
content/en/flux/use-cases/karmada.md

Update documentation for Helm GA
https://deploy-preview-1909--fluxcd.netlify.app/flux/guides/helmreleases/

Update documentation for Helm GA

---

hugo.yaml

We only support N-2 versions, that's 2.3, 2.2 and 2.1 so we shouldn't link to the 2.0 docs, anymore.

Mark version 2.2 as archived and remove 2.0 from versions dropdown

---

hack/import-calendar.py
hugo.yaml

Latest release is 2.3, we only support N-2 versions, that's 2.3, 2.2 and 2.1 so we shouldn't link to the 2.0 docs, anymore.

Update v2.1 version dropdown

---

hugo.yaml

We only support N-2 versions, that's 2.3, 2.2 and 2.1 so we shouldn't link to the 2.0 docs, anymore.

Remove 2.0 from version dropdown

---

hugo.yaml

We only support N-2 versions, that's 2.3, 2.2 and 2.1 so we shouldn't link to the 2.0 docs, anymore.

Remove 2.0 from versions dropdown

---

content/en/flux/monitoring/custom-metrics.md
content/en/flux/monitoring/metrics.md

- Fix the metrics deprecation link.
- Add new HelmRelease labels.
- Update HelmRelease version in custom metrics code snippet.

Update monitoring metrics docs

---

content/en/flux/releases/procedure.md

The instructions haven't reflected our actual procedure, anymore.
[preview](https://deploy-preview-1960--fluxcd.netlify.app/flux/releases/procedure/#distribution-minor-release-website)

Update website release instructions

---

content/en/_index.html

The Announce header on fluxcd.io main page can change to point at the new release blog, 🎉

Announce "Release 2.3" blog

---

content/en/ecosystem/index.md
content/en/support.md

Add the [flux-operator](https://github.com/controlplaneio-fluxcd/flux-operator) project to the ecosystem page and update the ControlPlane Enterprise for Flux links to point to the new [product website](https://fluxcd.control-plane.io).

Add flux-operator to ecosystem

---

content/en/ecosystem/index.md

Let's add information to the flux ecosystem ancillary tools about **flux2-bitbucketpipeline-dispatcher** that can help bitbucket cloud users with promotion automation.

Add bitbucketpipeline-dispather to Ancillary tools

---

content/en/flux/cmd/_index.md

A couple of more ways are available to install FluxCLI on Windows. This commit improves the documentation adding the winget option and the direct download option.

Add `winget` to CLI windows installation instructions

---

content/en/roadmap.md

Sync with: https://github.com/fluxcd/flux2/issues/4947

Update roadmap for Flux v2.4 (final)

---

content/en/flux/guides/image-update.md

This link is currently leading to 404, the PR fixes it.

Fix broken link in docs

---

content/en/flux/guides/webhook-receivers.md

Fixes fluxcd/flux2#2240
And some other minor issues I found while running through the webhook receiver guide:
* A tab character at the end of a copy-paste block that fouls things up
* The name of the receiver service is misnamed above a copy paste block

Fix inconsistencies in receiver guide

---

data/resources.yaml

There were a few articles hosted on weave.works but they are not accessible anymore, so had to be removed.
I am testing this feature to be sure I know how it works, since we do not have any live examples today!
(I'd like to add this one too:)
* https://medium.com/@mohamednoureldinn/fluxcd-azure-devops-oidc-authentication-916cc7bfe11f

Add the Headlamp article as a resource

---

assets/scss/_index.scss
data/resources.yaml
layouts/partials/resource.html
layouts/partials/template-resource.html

Testing the Resources / Article feature again. (also #2096)
Thanks Mohammed Nour for contributing this article about the new features in Flux 2.4 🎉 
(I asked if there was a branding image that goes with this blog, and it was suggested we just use the Flux logo as there isn't one.)

Add FluxCD Azure DevOps article resource

---

content/en/flux/cheatsheets/cel-healthchecks.md

Hi 👋🏼 
I added examples for cephcluster and clustersecretstore. I also updated the examples to include `healthCheckExprs` in all for consistency.
```yaml
ceph:
capacity:
bytesAvailable: 2047502884864
bytesTotal: 2400498229248
bytesUsed: 352995344384
lastUpdated: "2025-02-21T13:17:48Z"
fsid: ea343e3b-e0b6-402d-9eb0-3dfe7be41b27
health: HEALTH_OK
lastChanged: "2025-02-20T22:19:32Z"
lastChecked: "2025-02-21T13:17:48Z"
previousHealth: HEALTH_WARN
versions:
mds:
ceph version 19.2.1 (58a7fab8be0a062d730ad7da874972fd3fba59fb) squid (stable): 2
mgr:
ceph version 19.2.1 (58a7fab8be0a062d730ad7da874972fd3fba59fb) squid (stable): 2
mon:
ceph version 19.2.1 (58a7fab8be0a062d730ad7da874972fd3fba59fb) squid (stable): 3
osd:
ceph version 19.2.1 (58a7fab8be0a062d730ad7da874972fd3fba59fb) squid (stable): …
```

chore: add cephcluster and clustersecretstore examples

---

content/en/flux/installation/bootstrap/gitea.md

Forgejo is a fork of Gitea (see their [Comparison with Gitea](https://forgejo.org/compare-to-gitea/)).
I found [this discussion on the main flux repo](https://github.com/fluxcd/flux2/discussions/4924) and wanted to know if the gitea boostrap command works with Forgejo. I've described what I've done in a blog post titled [Flux and Forgejo](https://oligot.be/posts/flux-forgejo/) if you are interested but in a nutshell, you can use the exact same commands with a Forgejo server and it works !
This adds a small note on the gitea boostrap page to let people know that they can use Forgejo instead of Gitea with Flux.

Add a note on Forgejo support

---

.github/workflows/netlify.yml

I noticed after the Flux Bug Scrub last night, the website did not update this A.M.
It looks like we still have to update this workflow for each new minor/major release, to change the trigger branch.

Update website cron job for Flux 2.5

---

content/en/flux/guides/mozilla-sops.md

Adding a security notice that the example for SOPS pod patching is a bad security practice, it's just explaining the FluxCD behavior.

Security notice for SOPS pod patching

---

content/en/flux/cmd/_index.md

The installation script for the flux cli supports installation to a custom directory, this is now reflected in the documentation.

Add non-root install instructions

---

content/en/flux/cheatsheets/cel-healthchecks.md

Another quick documentation PR coming from fluxcd/kustomize-controller#1408. This PR adds a FAQ section to the CEL cheatsheet to mention CEL macros and discuss using `has` to deal with missing fields in flux kustomization `healthCheckExprs`
Closes fluxcd/kustomize-controller#1408

docs: add a FAQ section to CEL cheatsheet and discuss missing fields

---

data/resources.yaml

Any more talks out yet that we should add?
I see a lot of KubeCon talks have dropped on YouTube yesterday, but I did a quick search through the fluxcd.io/kubecon list and didn't find any of those talks out so far.

Add Cloud Native Telco Day Europe talk

---

content/en/flux/components/image/options.md

Part of: https://github.com/fluxcd/image-reflector-controller/pull/757

Add image-reflector-controller flag for BadgerDB GC

---

content/en/flux/use-cases/gh-actions-auto-pr.md

`create` events cannot be filtered with `branches`. `branches` be will silently ignored and match all create events.
See:
- https://docs.github.com/en/webhooks/webhook-events-and-payloads#create
- https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#create
- https://github.com/orgs/community/discussions/26286

Fix GitHub Action syntax error and filter with if statement

---

content/en/flux/installation/configuration/multitenancy.md
content/en/flux/security/_index.md

Add `Object-level Workload Identity RBAC` section to multi-tenancy docs with an example of how to disable the extra RBAC.

Add RBAC patch to remove Object-level Workload Identity

---

hack/import-flux2-assets.sh
layouts/shortcodes/blocks/flux_ui_galleries.html

I was able to fix the carousel
To get the build working at all on MacOS, first I had to:
* If a tool called "gsed" is available, use that one.
* If not, revert to "sed"
On MacOS sed is BSD sed and it fails around line 155, on the "Hack for fixing typo in the docs" regex

Fix carousel, fix local build on MacOS

---

content/en/flux/gitops-toolkit/packages.md

* [Promote OCI Repository API to v1](https://github.com/fluxcd/website/commit/bcfc8eeffc6a4f8dad9d91953738d5a356bf6546)
* [Promote Bucket API to v1](https://github.com/fluxcd/website/commit/f5542eba7f7391fc52b37ba01c1f24c70e303725)

Promote OCI Repository and Bucket API to v1

---

assets/scss/blocks/_nav.scss
package-lock.json

closes #2136 
If applied, this commit will ensure that the sidebar takes full available height while maintaining the scroll so that its obvious there is more content below

Fix left sidebar to use full height (#2136)

---

content/en/roadmap.md

I totally forgot to add these earlier, but here are my contributions that weren’t listed yet in the v2.7 roadmap:
- AWS S3 workload identity support
- Image automation GA preparation (shortNames)
- Kustomize v5.7.0 update (patch delete fix)
- Security enhancements section for RFC-0010 lockdown
- Deprecated template fields removal
Really appreciate all the great reviews! (@matheuscscp , @stefanprodan )

Add missing v2.7 contributions to roadmap

---

content/en/flux/monitoring/custom-metrics.md

Makes the `each.info` indentation of the first example same as the 2nd one:
https://github.com/fluxcd/website/blob/77178b1ac77dfc9c02edab7b5f1da3450ffb40cd/content/en/flux/monitoring/custom-metrics.md#L92-L95

docs: fix indentation in custom metrics example

---

content/en/flux/components/_index.md
content/en/flux/installation/_index.md
content/en/flux/installation/configuration/optional-components.md
content/en/roadmap.md

Also added the removal of deprecated APIs in 2.8

roadmap: Mark the 2.7 milestone as completed

---

content/en/flux/cmd/_index.md

Remove hardcoded version from the default install example and add a dedicated one for installing a specific version.

Update version in the Flux CLI install doc
