fluxcd/website

.editorconfig
README.md

This PR adds some more substantive pointers to the site README.

More info in README

---

config.toml

This adds a missing "r" to the word "descibe."

Correct minor typo in features

---

config.toml

Signed-off-by: Michael Irwin <mikesir87@gmail.com>

Update URLs to point to correct locations

---

assets/sass/style.sass
netlify.toml

Update Hugo to newer version

---

config.toml
layouts/_default/baseof.html
layouts/partials/notification.html

Thanks @hiddeco and @mewzherder for your work in #22 - combining the two here.
Closes: #18

V1 in maintenance

---

config.toml

Add link to GitOps Toolkit

---

config.toml

Fillt out blanks in resources and community

---

assets/sass/_card.sass
assets/sass/_hero.sass
assets/sass/style.sass
layouts/partials/home/community.html
layouts/partials/home/overview.html
layouts/partials/home/resources.html

Fixes #29 
Addresses part of #33

Various tweaks

---

config.toml

Update tagline and description to be about Flux v2

---

config.toml

@hiddeco I feel the features section still describes Flux v2
Would you prefer a detailed discussion of features (which would likely require a bit more background...?) - WDYT?
Addresses: #32

describe GitOps Toolkit

---

assets/sass/_notification.sass
assets/sass/style.sass
config.toml
layouts/partials/navbar.html
layouts/partials/notification.html

But with a message aimed at guiding people towards the Flux version 1 documentation.

Reinstantiate sitewide notification

---

config.toml

Addresses more of #32
Addresses part of #19

Various tweaks to homepage content

---

config.toml
layouts/partials/home/overview.html
layouts/partials/home/toolkit.html

Tweak Flux overview items

---

config.toml
layouts/partials/home/community.html
layouts/partials/home/resources.html

Add Y-margin to resource and community elements

---

layouts/partials/home/community.html
layouts/partials/home/resources.html

As it does not play nicely with Safari.

Temporarily disable equal height on cards

---

assets/sass/_card.sass
layouts/partials/home/community.html
layouts/partials/home/resources.html

Cards of equal height

---

Makefile
config.toml
netlify.toml

* Update Hugo version to 0.78.0
* Create different deploy strategy for branch deploys
* Enable garbage collection, minifying and Git info
* Change base URL in Hugo config to fix navbar link

Improve Netlify configuration

---

config.toml

Link to security document

---

assets/sass/style.sass
config.toml
layouts/partials/footer.html

Add link to socials in footer

---

config.toml
content/en/blog/2021-01-06-january-update.md

Add January 2021 blog post

---

.github/workflows/netlify.yml

Add cronjob to deploy 'main' on netlify (every 2h)

---

.github/workflows/netlify.yml
config.toml
external-sources/fluxcd/community

Add support page to website

---

content/en/blog/2021-02-01-february-update.md

@fluxcd/maintainers Anything missing you'd like to add?

Add February blog post

---

layouts/blog/rss.xml
layouts/partials/footer.html

Fixes: #88
Inspired by `Track3/hermit`.

Add rss feed

---

config.toml

Fix typo 'canaray'

---

config.toml
layouts/partials/home/resources.html

Adding youtube thumbnails to front page resources section.
I'm sure this can be done in a more failsafe and prettier way, but it's a start I guess. :innocent:

add youtube thumbnails

---

content/en/blog/2021-03-01-march-update.md

Needs https://github.com/fluxcd/community/pull/70 to land first.

blog post: Flux update March 2021

---

config.toml
layouts/partials/celebration.html
layouts/partials/home/family.html
layouts/partials/home/family/v1.html
layouts/partials/home/flux.html
layouts/partials/navbar.html

Break out changes from #101 that make the site look nicer - no announcement included yet.
I'll rebase #101 and #98 on top of this once it's merged.

Prep site for announcement

---

config.toml

Looks to be a typographic error

progress delivery -> progressive

---

external-sources/fluxcd/.github
external-sources/fluxcd/community
hack/gen-content.sh

New location is here: https://github.com/fluxcd/.github/blob/main/SECURITY.md

we moved the security file to fluxcd/.github

---

MAINTAINERS

Add Alison to maintainers

---

config.toml

Re-add missing Project links

---

content/en/docs/guides/mozilla-sops.md
content/en/docs/use-cases/azure.md
content/en/docs/use-cases/gh-actions-manifest-generation.md

Thanks Hidde for the heads-up!

Replace all !!! hints

---

hack/import-flux2-docs.sh
layouts/partials/page-meta-links.html

This allows us to override the 'edit this page' logic.
Fixes: #121

Add 'importedDoc' to frontmatter

---

i18n/en.toml

Not needed, cf https://github.com/google/docsy/blob/master/layouts/shortcodes/blocks/feature.html#L9
Fixes: #135

Remove superfluous '...' in ui_read_more

---

content/en/docs/use-cases/helm.md

Fix title of Helm use case doc

---

hack/import-flux2-docs.sh

Fix list of controller tags, version sort

---

hack/import-flux2-docs.sh

Use released version of 'flux' to generate cmd docs

---

assets/scss/blocks/_cncf.scss
layouts/shortcodes/blocks/cncf.html

Shrink CNCF section

---

.gitignore
Makefile
hack/import-flux2-assets.sh

Import flux install script

---

content/en/docs/use-cases/gh-actions-manifest-generation.md

This is the PR to fix issues I mentioned in #161

fixup links to use relref / inline href in alert

---

hack/import-flux2-assets.sh

Make script more explicit too.
Fixes: #124
Fix: #169

Fix duplicate titles in components docs

---

content/en/docs/_index.md

Pull in https://github.com/fluxcd/flux2/blob/main/docs/index.md from 968f249562b053e52eb9c915cca739a340b092a3

Import docs index from f/flux2

---

content/en/blog/2021-04-29-may-update.md

Fast follow to https://github.com/fluxcd/website/pull/184

May blog fixes

---

content/en/blog/2021-04-29-may-update.md

🤦  fix https://github.com/fluxcd/website/pull/185, also see #184

Fix image link

---

content/en/docs/use-cases/openshift.md

add openshift usecase

---

content/en/docs/use-cases/helm.md

Fix links on Helm doc

---

assets/scss/_adopters.scss

Thanks a lot @foot for the tip!

adopters page: center company logo in cards

---

config.toml

Point to #flux channel

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
DCO
MAINTAINERS
adopters/README.md

Changes:
- add myself to maintainers
- add DCO, CoC and contributing docs
- improve the adopters submission guide

Add DCO, CoC and contributing docs

---

hack/generate-adopters-pages.sh

shorten link to instructions

---

config.toml
layouts/partials/hooks/body-end.html
layouts/partials/hooks/head-end.html
layouts/partials/navbar.html

Use Algolia search

---

content/en/docs/guides/image-update.md

Updates the secret in place rather than delete and create.

Update Image Automation Docs 

---

layouts/partials/sidebar-tree.html

Override sidebar tree to not show extra search on mobile

---

content/en/docs/gitops-toolkit/_index.md
content/en/docs/gitops-toolkit/debugging.md
content/en/docs/gitops-toolkit/packages.md
content/en/docs/gitops-toolkit/source-watcher.md

Add dev guide on how to use the the GitOps Toolkit client libraries with Go.

Dev guide: Using the GitOps Toolkit APIs with Go

---

content/en/docs/migration/flux-v1-migration.md

add link to Flux Cloud

---

content/en/docs/guides/helmreleases.md
content/en/docs/guides/mozilla-sops.md
content/en/docs/guides/notifications.md
content/en/docs/guides/sealed-secrets.md
content/en/docs/guides/webhook-receivers.md

Signed-off-by: Manuel Morejon <manuel@mmorejon.io>

Fix links that goes to the installation page

---

content/en/docs/guides/notifications.md

Removed duplicate word

---

hack/gen-content.py

cf https://fluxcd.io/docs/contributing/flux2/

mark imported docs, this will remove the 'edit this page' link

---

config.toml
content/en/_index.html

- focus on new features in latest version, add link to migration docs
- make Adopters page more visible in nav
- smaller community logos

Rephrase landing somewhat

---

content/en/docs/migration/helm-operator-migration.md
content/en/docs/use-cases/helm.md

Signed-off-by: Michele Zuccala <michele@zuccala.com>

Fix helm remediation options naming

---

content/en/docs/guides/monitoring.md

Add docs on how to log into Grafana

---

content/en/docs/use-cases/azure.md

Notification controller assumes that it got fresh JWT tokens for usage.
Provide a small doc to explain how to do it
Signed-off-by: Edvin Norling <edvin.norling@xenit.se>

How to regenerate JWT tokens with Azure Event Hub

---

adopters/3-flux-v1.yaml

refer to bimspot logo for flux v1 use too

---

config.toml

Update Flux YouTube channel

---

Makefile
content/en/docs/use-cases/jenkins.md

This is the Jenkins+Flux use case guide that I've been promising to deliver
This works for me - any type of feedback is welcome! RFC

Jenkins + Flux guide

---

adopters/1-flux-v2.yaml
adopters/3-flux-v1.yaml
adopters/logos/quivr.svg
assets/scss/_adopters.scss

Signed-off-by: Frederik Baetens <baetens.fr@gmail.com>
If needed, i can convert the logo to png

Move Quivr to Flux2 adopters

---

content/en/docs/guides/repository-structure.md

This PR adds a guide to showcase several approaches of organizing repositories for a smooth GitOps experience with Flux.
Preview: https://deploy-preview-299--fluxcd.netlify.app/docs/guides/repository-structure

Ways of structuring your repositories

---

hack/generate-adopters-pages.py

I thought this looked nicer when the website is half width or less on my screen.

make adopters screen responsive based on screen width

---

content/en/blog/2021-05-31-june-update.md

Flux June 2021 update fix - add link to talk from May blog

---

content/en/docs/installation/_index.md

Address https://github.com/fluxcd/flux2/issues/1500 and https://github.com/fluxcd/flux2/issues/1166

Add Pod Security Policy section to install docs

---

Makefile
netlify.toml

- Align Netlify Hugo version with Makefile
- Use available `URL` value during production-build

Netlify fixes

---

content/en/legacy/_index.md
content/en/legacy/flux/_index.md

Change flux legacy nav

---

layouts/docs/baseof.html

all v1 docs are replaced with redirects

---

layouts/partials/navbar.html

fix navbar markup

---

.github/workflows/lychee-cron.yaml
.github/workflows/lychee-pr.yaml
Makefile
lychee.toml

Checks for broken links in files that have been chnaged in the PR.
Update Makefile with markdown-link-check install command

Enable markdwon-link-check on PR

---

content/en/legacy/flux/faq.md

Fix: fluxcd/flux#3490
Signed-off-by: Kingdon Barrett <kingdon@weave.works>

Fix broken link in legacy/flux/faq.md

---

adopters/1-flux-v2.yaml
adopters/3-flux-v1.yaml
adopters/logos/particule.svg

Hello
We'd like to add `particule.` to the list of Flux adopters :tada: 
Thanks in advance !

Add particule. to adopters

---

content/en/blog/2021-06-28-bug-scrub-announce.md

Bug Scrub Announce blog post

---

config.toml

make integrations more visible

---

config.toml

Also add logo to GH 
Fixes: #188

Add Github link

---

content/en/docs/guides/image-update.md

Signed-off-by: Rick Henry <rick.henry@assureddigitaltech.com>

Fix broken link in image update automation page

---

assets/scss/_adopters.scss
assets/scss/_buttons.scss
assets/scss/_variables_project.scss
assets/scss/blocks/_hero.scss
layouts/shortcodes/blocks/hero.html

Fixes https://github.com/fluxcd/website/issues/208
Fixes https://github.com/fluxcd/website/issues/369

adopters page card height and front page flat buttons

---

layouts/partials/page-meta-links.html

Resolves https://github.com/fluxcd/website/issues/163
Signed-off-by: Rishabh <rishabhbohra01@gmail.com>

"Create new issue" should point to .../issues/new/choose

---

content/en/_index.html

Thanks for the feedback @juozasg in https://github.com/fluxcd/website/commit/306c1712b18cc44c55e534e5842a01640bd34eb7#r52889485

Remove <hr>

---

assets/scss/_buttons.scss
assets/scss/blocks/_hero.scss

Fixes: #369 
Signed-off-by: Juozas <juozasgaigalas@gmail.com>

remove 1px green border from flat buttons

---

config.toml

disable foldable menu for now

---

.github/workflows/netlify.yml

Stops forks from failing repetitively due to lack of secrets

Only run action on main repo

---

assets/scss/_index.scss

Fix this:
Signed-off-by: Juozas <juozasgaigalas@gmail.com>

fix other flux projects button aligment on mobile

---

content/en/_index.html

update celebration to be about stable APIs

---

assets/scss/_index.scss
content/en/_index.html
layouts/shortcodes/blocks/contributors.html

Also includes a fix to make contributor icons have equal horizontal and vertical padding
@dholbach

Landing page section color fixes

---

content/en/docs/contributing/docs/writing-docs.md
layouts/shortcodes/codeblock.html
static/snippet/example.yaml

Adds the ability to read snippets from a file

Add code snippet embed support

---

assets/js/tabs.js
assets/scss/_tabs.scss
assets/scss/main.scss
content/en/docs/contributing/docs/writing-docs.md
content/en/docs/installation.md
layouts/partials/hooks/body-end.html
layouts/shortcodes/tab.html
layouts/shortcodes/tabs.html

Adds support for creating tabbed panes that contain code and/or markdown

Tab blocks with markdown and code snippet support

---

content/en/docs/faq.md

I added a FAQ section which describe "How to patch CoreDNS and other pre-installed addons?"

FAQ: How to patch CoreDNS and other pre-installed addons?

---

adopters/1-flux-v2.yaml
adopters/2-flagger.yaml
adopters/3-flux-v1.yaml
adopters/README.md
hack/adopters.py

Remove 'needs-name' logic - we ended up not using it.

---

hack/adopters.py
hack/contributors.py
hack/gen-content.py

Mostly just variable/constant names, indentation.

Fix a number of python lint issues

---

content/en/docs/use-cases/helm.md

...and update the example output to match what's generated with the command.

Update HelmRelease creation example

---

content/en/docs/installation.md

Fix install patch path

---

adopters/2-flagger.yaml

Signed-off-by: Marcel Gädigk <marcel.gaedigk@lovoo.com>

Add LOVOO to flagger  adopters

---

content/en/docs/get-started.md
content/en/docs/use-cases/azure.md

This should be merged after flux2 v0.16.2 is released.

Use flux get --watch in docs

---

content/en/_index.html

Explicitly link to Community section

---

assets/scss/_index.scss
assets/scss/blocks/_hero.scss
content/en/_index.html
layouts/shortcodes/blocks/featureitem.html

Fixes https://github.com/fluxcd/website/issues/410

Landing page flux in short and other section layout adjustments

---

content/en/blog/2021-01-06-january-update.md
content/en/blog/2021-02-01-february-update.md
content/en/blog/2021-03-01-march-update.md
content/en/blog/2021-03-31-april-update.md
content/en/blog/2021-04-29-may-update.md
content/en/blog/2021-05-31-june-update.md
content/en/blog/2021-07-02-july-update.md
content/en/blog/2021-08-02-august-update.md
content/en/docs/_index.md

Point to calendar instead

---

config.toml
content/en/_index.html
content/en/blog/2021-02-01-february-update.md
content/en/blog/2021-03-01-march-update.md
content/en/blog/2021-03-31-april-update.md
content/en/blog/2021-04-29-may-update.md
content/en/blog/2021-05-31-june-update.md
content/en/blog/2021-07-02-july-update.md
content/en/blog/2021-08-02-august-update.md
content/en/resources.md

Add simple resources page

---

content/en/resources.md

When copying the videos over, I made a couple of copy/paste mistakes. Here's a fix.

resources section: fix links / videos

---

content/en/legacy/flux/references/daemon.md
content/en/legacy/flux/references/fluxctl.md
content/en/legacy/flux/tutorials/get-started-kustomize.md

This is the oldest open issue on the Flux v1 repo, and it can be closed with this docs update.
* fluxcd/flux#2998
Added one more:
* fluxcd/flux#3192
Signed-off-by: Kingdon Barrett <kingdon@weave.works>

Fix minor omission from Flux v1 docs

---

content/en/docs/get-started.md
content/en/docs/installation.md

Changes:
- Normalise Flux CLI install docs
- Add customisation task to get started guide 
- Fix broken links in get started
- Fix alert formatting in get started

Docs improvements 

---

content/en/endorsements.yaml
content/en/resources.md

add Microsoft talk to resources and 'user stories' on the landing page

---

config.toml
content/en/blog/2021-02-01-february-update.md
content/en/blog/2021-03-01-march-update.md
content/en/blog/2021-07-02-july-update.md
content/en/docs/migration/faq-migration.md
content/en/docs/migration/timetable.md
content/en/roadmap.md
static/_redirects

Move roadmap out of docs

---

content/en/docs/use-cases/helm.md

Refer to the conversation in PR #414.

Update helm.md - 2

---

content/en/roadmap.md

link checker didn't catch them :-(

Fix links in roadmap doc

---

content/en/docs/use-cases/openshift.md

fix resource notes

---

content/en/resources.md

fix typos on resources page

---

config.toml

Signed-off-by: Max Jonas Werner <mail@makk.es>

fix: branding link lead to 404

---

content/en/docs/gitops-toolkit/packages.md

Signed-off-by: Rishabh Bohra <rishabhbohra01@gmail.com>

docs: Change word imame to image

---

assets/scss/blocks/_cncf.scss
assets/scss/blocks/_nav.scss
layouts/partials/navbar.html

Fixes this and cleans up the navbar template

Notice bar responsive sizing fixup

---

content/en/_index.html

fixup - link is not rendered

---

content/en/resources.md

Typo fix in intro paragraph + added Terraform Community Office Hours featuring FluxCD Provider for Terraform by Philip Laine (from 9 Sep 2021)

Fixed typo + add video to resources

---

Dockerfile
Makefile

Use ARG in Dockerfile to pass hugo version for image name.

Define hugo version once

---

content/en/resources.md

Added new video: Build a Smooth CI/CD Pipeline Using GitOps and Flux with Smaïne Kahlouch & Matheiu Gillot (at DevSecOps Road Trip: France) from 14 Sep 2021.
@dholbach - could you please verify I've done this correctly and it renders ok using the url & thumbnail instead of the youtube shortcut? I was trying to link it so that it would start at the correct timestamp. Thanks in advance! :) 

Add new video to resources

---

content/en/_index.html

mention incubation and tech-radar at the top

---

.github/workflows/lychee-pr.yaml

Only run link check if there are file changes

---

content/en/_index.html

update celebration bar for the gitops-one-stop-shop-event

---

content/en/_index.html

Update front page description

---

hack/adopters.py
hack/contributors.py
hack/gen-content.py
hack/import-calendar.py

makes it easier to run on different systems where python3 is in a different place

use bin env instead of bin

---

assets/scss/_terminal.scss

There was a much simpler solution for #301

Fix terminal reflowing during loading

---

assets/scss/_index.scss
assets/scss/blocks/_calendar.scss
assets/scss/blocks/_hero.scss
content/en/_index.html
layouts/shortcodes/blocks/hero.html
layouts/shortcodes/blocks/resource.html

Updated sizing and padding for fonts and surrounding elements to increase density of text in the front page so that it looks less zoomed out. Also made small changes to the H1 text that read better to me. Next step, is link colors/decorations to increase visibility. 
Please provide feedback

Review fonts 

---

content/en/blog/2021-09-29-server-side-reconciliation-is-coming.md

add blog post about server-side reconciliation

---

content/en/resources.md

Add Kingdon & Jason's Flux, Flagger, Linkerd talk from 28-Sep-2021 CloudNative @Scale Meetup. :) 

Add latest video from 28-Sep to Resources

---

content/en/blog/2021-10-01-october-update.md

add October update

---

content/en/blog/2021-09-29-server-side-reconciliation-is-coming.md

SSA: #1.16.11, not 1.6.11

---

content/en/_index.html

Point to all of our events in October

---

content/en/blog/2021-09-29-server-side-reconciliation-is-coming.md

Will update https://discuss.kubernetes.io/t/flux-server-side-reconciliation-is-coming/17581 as well.

point to newest image for testing

---

content/en/docs/migration/faq-migration.md

Fix: https://github.com/fluxcd/flux2/issues/614

Add `fluxcd.io/ignore` equivalent to migration FAQ

---

.gitignore
Makefile

https://www.docsy.dev/docs/adding-content/diagrams-and-formulae/#diagrams-with-diagramsnet
https://github.com/google/docsy/pull/529

Update docsy theme, now with draw.io support

---

content/en/resources.md

@staceypotter Is this all the ones you were expecting me to add?

add new resources from gitops one stop shop event

---

assets/scss/blocks/_nav.scss

Search input text should be vertically centered

---

content/en/docs/installation.md
content/en/docs/use-cases/aws-codecommit.md
lychee.toml

Initial run at adding a setup of AWS CodeCommit with Flux.
I'm not sure if I've missed anything here, I need to run through it and make some notes for possible issues.
Any feedback at this point is appreciated.

Add AWS CodeCommit use case page

---

content/en/resources.md

Added videos from GitOpsCon NA 2021, KubeCon NA 2021, Philip's Controller + Terraform talk at HashiCon, Stefan's technically speaking chat w/Chris Wright.
@dholbach let me know if things look ok here - tried to comment out some dates to more easily visualize the order of things. 
Thanks!

Added a slew of new resources

---

.github/workflows/update-maintainers-files.yaml

add job to update MAINTAINERS file automatically

---

content/en/roadmap.md

Add the multi-tenancy RFCs to roadmap.

Update roadmap with multi-tenancy RFCs

---

.github/workflows/update-maintainers-files.yaml

fix job to clean up /temp before submitting PR

---

content/en/legacy/flux/faq.md

docs(faq.md): Flux CD → Flux

---

content/en/docs/use-cases/jenkins.md

docs(jenkins.md): Flux CD → Flux

---

content/en/legacy/helm-operator/get-started/quickstart.md

docs(quickstart.md): Flux CD → Flux

---

content/en/legacy/helm-operator/get-started/using-helm.md

docs(using-helm.md): Flux CD → Flux

---

content/en/docs/guides/mozilla-sops.md

This adds a new section describing how to setup encryption with HashiCorp Vault.

SOPS: How to setup in-cluster secrets decryption with HashiCorp Vault

---

hack/gen-content.py

- improve link_mapping (all files from external-sources), which now also stores the repository - this makes rewriting of links more accurate
- check each link only once, no matter how often it is found
- realise 4 different types of links in markdown
Fixes: #680

Fix rewriting of links

---

content/en/docs/migration/timetable.md
content/en/docs/security/_index.md

@squaremo follow-up to your post-merge reviews of https://github.com/fluxcd/website/pull/641. I want to add additional things to it apart from addressing your comments, but if you can please review these commits that do, we could get that part in while I/we work on adding additional info in follow-up PRs. Thanks!

Update security doc landing page

---

content/en/docs/faq.md

Add FAQ for when to expect release schedule info

---

content/en/docs/use-cases/openshift.md

This PR fix OpenShift instructions required to run before installing Flux v0.26.

update openshift instructions for Flux v0.26

---

content/en/integrations.md

Add renovatebot, flux-check-hook, s3-auth-proxy to prepopulate.

Add ancillary tools section

---

content/en/integrations.md

Back out renovatebot until upstream issue 13952 is fixed

---

content/en/_index.html
content/en/blog/2021-01-06-january-update.md
content/en/blog/2021-08-02-august-update/index.md
content/en/blog/2021-08-30-september-update/index.md
content/en/blog/2022-01-31-january-update/index.md
content/en/endorsements.yaml
content/en/resources.md

Deemphasise 'v2' some more, also remove 'flux cd' mentions

---

content/en/docs/guides/image-update.md

Add extra docs for azure

---

.github/workflows/lychee-cron.yaml
.github/workflows/lychee-pr.yaml

Following up on #742, we are disabling link checking for now

Disable link checking for now

---

content/en/docs/_index.md

Signed-off-by: mewzherder <tamao@weave.works>

Updated basic description

---

content/en/docs/guides/flux-e2e.md

Signed-off-by: Tom Huang <tom.huang@weave.works>

add image automation and reflector controller doc

---

content/en/docs/guides/flux-e2e.md

Removing a git merge conflict apparently committed and pushed in error.
@kingdonb please review and correct if this is not what you were going for....

Remove e2e docs section 6 merge conflict

---

content/en/legacy/helm-operator/helmrelease-guide/reconciliation-and-upgrades.md

Bellow->Below
Signed-off-by: Satyam Kapoor <satyam@satyamkapoor.com>

fix tiny typo

---

content/en/docs/cheatsheets/_index.md
content/en/docs/cheatsheets/bootstrap.md
content/en/docs/installation.md

Showcase various configurations of Flux controllers at bootstrap time.
Preview here: https://deploy-preview-779--fluxcd.netlify.app/docs/cheatsheets/bootstrap/
Ref: #749

Add Bootstrap cheatsheet

---

config.toml
content/en/ecosystem.md
static/_redirects

Rename integrations page to Flux Ecosystem

---

content/en/docs/use-cases/openshift.md

update OpenShift instructions for v0.27.0

---

content/en/docs/use-cases/openshift.md

update openshift instructions

---

content/en/blog/2022-02-22-security-fuzzing.md

Thanks @pjbgf for the initial review.

Add security blog post about fuzzing

---

content/en/blog/2021-09-17-gitops-one-stop-shop-event/index.md
content/en/docs/components/helm/_index.md
content/en/docs/components/image/_index.md
content/en/docs/components/kustomize/_index.md
content/en/docs/components/notification/_index.md
content/en/docs/components/source/_index.md
content/en/docs/guides/monitoring.md

Add missing alt tags for images

---

content/en/_index.html
layouts/shortcodes/blocks/announce.html

Make announce color configurable

---

config.toml
content/en/docs/flux-e2e.md
content/en/docs/guides/flux-e2e.md

This draft is intended to be written in the style of https://www.envoyproxy.io/docs/envoy/v1.19.1/intro/life_of_a_request based on https://github.com/fluxcd/website/issues/586 – an issue in our Flux Security Audit Follow-Up project.
I am interested in feedback about the structure, style, and goals of the document. Welcome to reply in this PR with feedback of any kind.
Also I am aware of the potential for overlap between this document and those that are produced in #595, #641, and #711. (Aim not to repeat ourselves in this document; if there is already a suitable doc available to describe the feature, defer to it.)

Flux from End-to-End

---

content/en/resources.md

Added YT video of: Managing Thousand of Clusters and Their Workloads - Max Jonas Werner (2022-03-02)

Add Max's video from 2022-03-02

---

content/en/blog/README.md

explain the technical bits of writing blog posts

---

content/en/docs/installation.md

Change in line 528. `kustomization.yam`l to `kustomization.yaml`

Fix highlight in "Customize Flux manifests"

---

content/en/blog/README.md
content/en/docs/contributing/docs/_index.md

reflow blog instructions a little, add more detail, link to them

---

Makefile
layouts/blog/list.html
netlify.toml

update docsy and hugo

---

netlify.toml

Brings fix for HTML comments regression in 0.94.0

Update Hugo to 0.94.1

---

content/en/_index.html
content/en/docs/_index.md

Copy 'flux in short' overview to docs/ landing page

---

content/en/docs/guides/mozilla-sops.md

Add instructions for SOPS with Age and Vault instead of linking to the API spec.

Update SOPS Age and Vault instructions

---

config.toml
layouts/docs/baseof.html

Enable "tag cloud" for blog only

---

content/en/blog/2021-10-01-october-update.md

fix blog tag: should be monthly-update

---

content/en/docs/faq.md

Add step-by-step guide on how to safely move resources from one dir to another.

FAQ:  How can I safely move resources from one dir to another

---

content/en/docs/cheatsheets/bootstrap.md

Ref:
- https://github.com/fluxcd/kustomize-controller/issues/569
- https://github.com/fluxcd/helm-controller/issues/415

cheatsheet: Using HTTP/S proxy for egress traffic

---

content/en/docs/faq.md
content/en/docs/flux-e2e.md
content/en/docs/get-started.md
content/en/docs/guides/helmreleases.md
content/en/docs/guides/mozilla-sops.md
content/en/docs/guides/sealed-secrets.md
content/en/docs/guides/webhook-receivers.md
content/en/docs/migration/helm-operator-migration.md
content/en/docs/use-cases/gh-actions-manifest-generation.md
content/en/docs/use-cases/helm.md
content/en/roadmap.md

⚠️ Should be merged after flux2 v0.28.0 release
Depends on:
- https://github.com/fluxcd/flux2/pull/2550
- https://github.com/fluxcd/website/pull/840

Update samples to v1beta2 source API

---

content/en/docs/faq.md

⚠️ Should be merged after flux2 v0.28.0 release
Depends on: https://github.com/fluxcd/flux2/pull/2550

Add `kustomize.toolkit.fluxcd.io/ssa: merge` to FAQ

---

content/en/resources.md

Add 4 videos from March to Resources

---

layouts/shortcodes/blocks/resource.html

resolve https://github.com/fluxcd/website/issues/864

Accessibility add alt to images

---

content/en/blog/2022-04-04-march-update/index.md

fix link to tf-controller release page

---

assets/scss/blocks/_hero.scss

resolve https://github.com/fluxcd/website/issues/874

ui update on mobile (hero block)

---

assets/scss/_index.scss
assets/scss/blocks/_nav.scss
layouts/partials/navbar.html

resolve https://github.com/fluxcd/website/issues/878

add toggle button to collapse navigation on mobile

---

content/en/blog/2022-04-13-contributing-to-flux.md

add blog to show how to contribute to Flux

---

content/en/resources.md

Deploy preview:
https://deploy-preview-884--fluxcd.netlify.app/resources/

Add Flux+Starboard video to Resources

---

assets/scss/_adopters.scss

resolve https://github.com/fluxcd/website/issues/883

fix slider on mobile

---

hack/import-flux2-assets.sh

retry getting tar as well

---

assets/scss/_adopters.scss

resolve https://github.com/fluxcd/website/issues/888

fix adopters cards on mobile

---

assets/scss/_page.scss

resolve https://github.com/fluxcd/website/issues/896

fix link on mobile

---

content/en/blog/2021-10-29-november-update/index.md
content/en/blog/2021-11-30-december-update/index.md
content/en/blog/2022-03-01-february-update/index.md
content/en/blog/2022-04-04-march-update/index.md
content/en/blog/2022-04-13-contributing-to-flux.md
content/en/ecosystem.md

resolve https://github.com/fluxcd/website/issues/899

update docs links

---

content/en/_index.html
content/en/legacy/flux/_index.md
content/en/legacy/flux/introduction.md
layouts/shortcodes/blocks/project.html

fix project buttons on landing page, adjust links too

---

content/en/docs/installation.md

Solves https://github.com/fluxcd/flux2/discussions/2694

Add the deploy key rotation procedure to install docs

---

content/en/blog/2022-05-04-april-update.md

Add April 2022 monthly update

---

content/en/blog/2022-04-04-march-update/index.md
content/en/blog/2022-04-13-contributing-to-flux.md
content/en/blog/2022-05-04-april-update.md

cancel Bug Bash participation

---

content/en/ecosystem.md

Signed-off-by: Christian Berendt <berendt@23technologies.cloud>

ecosystem: add 23technologies/gardener-extension-shoot-flux

---

content/en/blog/2022-05-10-may-2022-security-announcement.md

Blog post: May 2022 Security Announcement

---

Makefile
layouts/partials/hooks/body-end.html
layouts/partials/hooks/head-end.html
layouts/partials/page-meta-links.html

- Move to Algolia v3: https://docsearch.algolia.com/docs/docsearch-v3/
- Sync layout/partials changes to our overrides

Update docsy to latest

---

content/en/blog/2022-05-12-flux-at-kubecon-eu-2022/index.md

update project meeting schedule

---

content/en/resources.md

add Techno Tim's Flux intro

---

assets/scss/_responsive-video.scss
assets/scss/main.scss
layouts/shortcodes/youtube.html

resolve https://github.com/fluxcd/website/issues/913

update youtube shortcode

---

layouts/shortcodes/youtube.html

remove unnecessary styles

---

hack/import-calendar.py

We now have one all-day event reminder in our calendar. Make sure we do
the import right.
Fixes: #945

Fix calendar import script

---

content/en/resources.md

add Somtochi's lightning talk from GitOpsCon

---

content/en/docs/guides/mozilla-sops.md
content/en/docs/use-cases/gcp-source-repository.md

Add Google Cloud Source Repository docs

---

content/en/blog/2022-06-01-may-update/index.md

[Signed-off-by: Daniel Holbach <daniel@weave.works>](https://github.com/fluxcd/website/pull/971#pullrequestreview-993054808)

typo: re-add team

---

content/en/docs/guides/mozilla-sops.md

Update azure docs on mozilla sops

---

content/en/docs/use-cases/gh-actions-helm-promotion.md

Signed-off-by: David Harris <david.harris@weave.works>

fix typo in example workflow

---

content/en/docs/components/helm/options.md
content/en/docs/components/image/options.md
content/en/docs/components/kustomize/options.md
content/en/docs/components/notification/options.md
content/en/docs/components/source/options.md

Fix: https://github.com/fluxcd/flux2/issues/2654

Document the controllers flags

---

assets/scss/_index.scss
layouts/shortcodes/blocks/project.html

resolve https://github.com/fluxcd/website/issues/965

update Flagger on mobile (ui)

---

content/en/ecosystem.md

Signed-off-by: Jianbo Sun <jianbo.sjb@alibaba-inc.com>

Feat: add kubevela as one of the Integration

---

content/en/docs/use-cases/karmada.md

Add “Karmada + Flux” user guide to increase the use case of flux in multi-cluster application distribution.
**Special notes:**
/cc @stefanprodan

Add "Karmada + Flux" user guide

---

content/en/docs/use-cases/running-jobs.md

Adds documentation for how to run Jobs with Flux with depending Kustomizations.

Add documentation for how to run jobs with Flux

---

content/en/docs/components/helm/options.md
content/en/docs/components/notification/options.md
content/en/docs/components/source/options.md

Fix concurrent description for notification-controller/helm-controller/source-controller

Fix concurrent description

---

hack/import-flux2-assets.sh

Use GITHUB_TOKEN to download Flux assets

---

Makefile
layouts/blog/baseof.html
layouts/docs/baseof.html
layouts/partials/page-meta-links.html
layouts/partials/sidebar-tree.html

Updating all the relevant overridden partials in the PR. 

update docsy to most recent (includes tabpane fixes)

---

assets/scss/_highlight.scss
assets/scss/main.scss

resolve https://github.com/fluxcd/website/issues/995

Update code block on mobile

---

assets/scss/_sidebar.scss
assets/scss/main.scss

resolve https://github.com/fluxcd/website/issues/1002

fix docs arrow on hover

---

hack/contributors.py

add missing repositories

---

assets/scss/_index.scss

resolve https://github.com/fluxcd/website/issues/433

update contributors on mobile

---

content/en/ecosystem.md

Ref: https://github.com/fluxcd/webui/pull/65

Add Flux UI section to the ecosystem page

---

content/en/docs/migration/flux-v1-migration.md

Signed-off-by: William Brode <williambrode@gmail.com>

Add links for flux v1 uninstall

---

content/en/docs/components/image/options.md

Depends on https://github.com/fluxcd/image-automation-controller/pull/388

Add --ssh-hostkey-algos to IAC docs

---

content/en/blog/2021-06-28-bug-scrub-announce.md
content/en/blog/2021-09-17-gitops-one-stop-shop-event/index.md
content/en/blog/2022-05-12-flux-at-kubecon-eu-2022/index.md
content/en/blog/2022-05-25-kubecon-eu-2022-wrapup/index.md
content/en/blog/2022-06-03-gitops-days-2022/index.md
content/en/blog/2022-07-04-june-update/index.md

add missing blog tags

---

content/en/blog/2022-07-04-june-update/index.md

back out WGE bit for now

---

content/en/ecosystem.md

Fixes: #947
As discussed in the issue, all of the vendors have gone on the record to talk about their Flux integration, so should be fine to be mentioned here. :-)

Ecosystem: add section about products/services

---

content/en/blog/2022-07-04-june-update/index.md

Add CTA to Weave GitOps entry

---

assets/scss/blocks/_nav.scss

Fix alignment as well.
Fixes: #1031

Apply styling to new search input

---

content/en/docs/cheatsheets/troubleshooting.md
content/en/docs/faq.md

Thanks @pjbgf for providing content

Add troubleshooting cheatsheet

---

content/en/blog/2022-07-11-gitopsdays-vscode-extension-demo/index.md

Sorry the #1034 didn't have @staceypotter 's commit - my mistake.

Changed tense in a few spots to be consistent

---

content/en/flagger/SUMMARY.md
content/en/flagger/install/flagger-install-on-alibaba-servicemesh.md
content/en/flagger/tutorials/contour-progressive-delivery.md
content/en/flagger/tutorials/keda-scaledobject.md
content/en/flagger/usage/how-it-works.md
content/en/flagger/usage/metrics.md

update Flagger docs to 1.22

---

README.md

Thanks @Santosh1176 for spotting

Add jq to install instructions

---

Makefile
assets/scss/_adopters.scss
assets/scss/_ecosystem.scss
assets/scss/_sidebar.scss
assets/scss/main.scss
content/en/docs/cmd/_index.md
content/en/docs/installation.md
layouts/partials/sidebar-tree.html

update to new versions of themes (docsy, gallery)

---

content/en/docs/security/_index.md

drop note about security page being WIP

---

content/en/docs/use-cases/azure.md

Signed-off-by: Soule BA <soule@weave.works>

Update Azure doc now that we support OCI Helm Repositories

---

assets/scss/blocks/_blog.scss

resolve https://github.com/fluxcd/website/issues/834

fix deprecation notice blog page

---

content/en/docs/security/best-practices.md

- Small fixes to security best practices doc involving some grammar fixes, spelling, and some formatting changes

Small nits and Grammar Fixes for Security Best Practices

---

assets/scss/blocks/_nav.scss

resolve https://github.com/fluxcd/website/issues/1051

update search on mobile

---

content/en/_index.html

Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>
Updates the resources section on the homepage with updated YouTube resources.
This PR would resolve issue [#941](https://github.com/fluxcd/website/issues/941#issue-1236770970)

Updating resources section on Homepage

---

content/en/flagger/tutorials/keda-scaledobject.md
content/en/flagger/tutorials/zero-downtime-deployments.md

flagger: add KEDA tutorial to nav

---

content/en/docs/faq.md

Mention UIs in Flux FAQ

---

content/en/blog/2022-08-02-july-update/index.md

blog: Change text perspective of ecosystem entries

---

content/en/docs/cheatsheets/oci-artifacts.md
content/en/docs/components/_index.md
content/en/docs/concepts.md
content/en/docs/guides/notifications.md
hack/import-flux2-assets.sh

Preview: https://deploy-preview-1073--fluxcd.netlify.app/docs/cheatsheets/oci-artifacts/
Part of: https://github.com/fluxcd/flux2/issues/2948

Add Flux OCI documentation and example workflows

---

content/en/docs/guides/helmreleases.md

Signed-off-by: Benny <benjamin@bertow.com>

Fix link to ConfigMap generator documentation

---

Makefile
layouts/blog/list.html

Update docsy to latest main

---

assets/scss/_index.scss

resolve https://github.com/fluxcd/website/issues/1056

fix youtube video on landing page

---

Makefile
config.toml
layouts/blog/baseof.html
layouts/partials/page-meta-links.html

update to new font awesome (follow docsy)

---

MAINTAINERS

add emeriti

---

netlify.toml

https://docs.netlify.com/routing/headers/

add custom HTTP headers

---

content/en/blog/2022-05-04-april-update.md
content/en/blog/2022-06-01-may-update/index.md

resolve https://github.com/fluxcd/website/issues/1098

update links in docs

---

content/en/docs/cheatsheets/bootstrap.md

Add bootstrap patch example for enabling notifications for third party controllers.

Add example for enabling notifications for 3rd party controllers

---

content/en/flagger/dev/dev-guide.md
content/en/flagger/tutorials/keda-scaledobject.md
content/en/flagger/usage/how-it-works.md

update flagger docs to 1.22.2

---

content/en/docs/gitops-toolkit/source-watcher.md

Update prerequisites and Flux API version.

Update source watcher guide

---

config.toml
content/en/flux/flagger.md
layouts/partials/navbar.html

add dropdown to be able to switch between docs

---

content/en/flux/security/secrets-management.md

Signed-off-by: David Harris <david.harris@weave.works>
New PR having closed https://github.com/fluxcd/website/pull/1111

typos and grammatical changes to secrets management

---

layouts/partials/navbar.html

resolve https://github.com/fluxcd/website/issues/1126

fix docs drop-down on mobile

---

netlify.toml

https://github.com/gohugoio/hugo/releases/tag/v0.102.3

update hugo to 0.102.3

---

content/en/flux/cmd/_index.md

This will allow us to revert fluxcd/flux2#3034

Use cascade feature for imported cli docs

---

Makefile
config.toml
layouts/404.html
layouts/blog/baseof.html
layouts/blog/list.html
layouts/docs/baseof.html
layouts/partials/favicons.html
layouts/partials/hooks/body-end.html
layouts/partials/hooks/head-end.html
layouts/partials/navbar.html
layouts/partials/page-meta-links.html
layouts/partials/sidebar-tree.html
netlify.toml

Update to latest docsy

---

content/en/blog/2022-09-05-august-update/index.md

add FSA link, expand on Weave GitOps

---

content/en/flux/cheatsheets/oci-artifacts.md

Signed-off-by: Max Jonas Werner <max@e13.dev>

fix typo in OCI cheatsheet

---

content/en/blog/2022-09-01-manage-kyverno-policies-as-ocirepositories/index.md

blog: add oci tag to post

---

config.yaml

Signed-off-by: Daniel Holbach <daniel@holba.ch>

move search config under params

---

content/en/resources.md

Signed-off-by: Vanessa Abankwah  <96237690+VanessaWeaveworksK8S@users.noreply.github.com>

Adding GitOps Days 2022 Videos

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1163

update hugo to 0.104.1

---

content/en/flux/get-started.md

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

docs: fix flux get kustomizations cmd output

---

Makefile

update theme versions

---

content/en/blog/2022-06-01-may-update/index.md
content/en/blog/2022-08-02-july-update/index.md
content/en/blog/2022-10-04-september-update/index.md

fix links and update GitOpsCon schedule

---

adopters/3-flux-v1.yaml

adopters: update Weaveworks use

---

layouts/partials/docs/legacy-warning.html

specify when v1 goes EOL

---

content/en/_index.html

celebrate OCI support

---

Makefile
content/en/blog/2022-05-25-kubecon-eu-2022-wrapup/index.md
content/en/ecosystem/index.md
layouts/blog/list.html
layouts/partials/navbar.html

Apply upstream changes to minimise our diff

Update Docsy and Gallery versions

---

content/en/.gitignore
content/en/_index.html
content/en/resources.yaml
hack/resources.py
layouts/shortcodes/blocks/resources_section.html

Write resources section on mainpage from YAML

---

assets/scss/_index.scss
assets/scss/blocks/_calendar.scss
content/en/_index.html

landing page: Move calendar and community up

---

content/en/flux/faq.md

Explain why we don't allow the Kustomize Helm plugin and show how Helm works with Flux.

FAQ: Should I be using Kustomize Helm chart plugin?

---

content/en/flux/cheatsheets/oci-artifacts.md
content/en/flux/faq.md

Part of: https://github.com/fluxcd/flux2/issues/3228

Add Hem chart verification section to OCI docs 

---

content/en/flagger/_index.md
content/en/flagger/install/flagger-install-on-alibaba-servicemesh.md
content/en/flagger/install/flagger-install-on-eks-appmesh.md
content/en/flagger/install/flagger-install-on-google-cloud.md
content/en/flagger/install/flagger-install-on-kubernetes.md
content/en/flagger/install/flagger-install-with-flux.md
content/en/flagger/usage/alerting.md

Publish Flagger v1.24.0 docs

---

go.mod
go.sum

switch to released version of docsy

---

content/en/blog/2022-10-26-cncf-talk-flux-oci/index.md

fix: add blog post description

---

content/en/ecosystem/index.md

updating Weaveworks GitOps enterprise URL 
Signed-off-by: Mohamed F. Ahmed <MohamedFAhmed@users.noreply.github.com>

New Weaveworks GitOps enterprise URL

---

adopters/1-flux-v2.yaml

Signed-off-by: Steve Wilkerson <steve.wilkerson@jbhunt.com>

Add J.B. Hunt to adopters

---

config.yaml

update youtube channel url and description

---

layouts/shortcodes/blocks/calendar.html

Fix calendar sign-up information link

---

layouts/partials/hooks/body-end.html

simplify search - we don't distinguish between current/legacy any more

---

assets/scss/_index.scss
content/en/.gitignore
content/en/_index.html
hack/import-calendar.py
layouts/shortcodes/blocks/next_event.html

Promote next event

---

content/en/blog/2022-11-01-november-update/index.md

add October blog post

---

content/en/flux/migration/_index.md

Add resources for migrating

---

content/en/resources.yaml

Signed-off-by: Vanessa Abankwah <96237690+vanessaabankwah@users.noreply.github.com>

Added GitOps Con Videos

---

content/en/blog/2022-11-11-prove-the-authenticity-of-helm-charts/index.md

fix blog date so it shows up today

---

content/en/flagger/faq.md
content/en/flagger/tutorials/istio-progressive-delivery.md
content/en/flagger/usage/deployment-strategies.md

update flagger docs to 1.25.0

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1272

update hugo to 0.106.0

---

content/en/blog/2022-09-01-manage-kyverno-policies-as-ocirepositories/index.md
content/en/blog/2022-10-04-september-update/index.md
content/en/blog/2022-11-11-prove-the-authenticity-of-helm-charts/index.md
content/en/flux/migration/_index.md
content/en/flux/security/best-practices.md
content/en/roadmap.md

flux/migration: update wording and color slightly

---

content/en/flux/use-cases/gh-actions-auto-pr.md

Fix: https://github.com/fluxcd/flux2/issues/3343
Signed-off-by: Paul Lockaby <633173+plockaby@users.noreply.github.com>

update wording for changes to force-push

---

content/en/flagger/dev/release-guide.md

Add steps to release load tester

update flagger release guide

---

content/en/flagger/tutorials/gatewayapi-progressive-delivery.md

update gateway api docs to v1beta1

---

content/en/resources.yaml

@staceypotter 
Signed-off-by: Vanessa Abankwah <96237690+vanessaabankwah@users.noreply.github.com>

Update KubeCon NA 2022 videos

---

hack/new-update-post.py
templates/monthly-update.md

This will be an experiment to see if we can spare ourselves the pain of going from Google Docs to .docx to .md for this very regular set of communications.

Add template for monthly update blog posts

---

content/en/flux/migration/flux-v1-migration.md

Signed-off-by: surya <suryamailsyou@gmail.com>

docs: Flux-v1-migration add details about flux2's server side validation

---

assets/scss/_terminal.scss
layouts/shortcodes/blocks/hero.html

resolve https://github.com/fluxcd/website/issues/1292

fix 768px arrow moves to another line

---

content/en/blog/2022-12-01-november-update/index.md

moved Nov 29 & Nov 30 WOUGs to "upcoming"

---

content/en/blog/2022-12-01-november-update/index.md
templates/monthly-update.md

The URL was wrong. Change it to "november" and set an alias.

update blog post url

---

assets/scss/_adopters.scss

resolve https://github.com/fluxcd/website/issues/1295

ui update carousel

---

config.yaml
go.mod
go.sum

update themes - mermaid is now enabled in docsy on-the-fly

---

content/en/blog/2022-12-01-november-update/index.md
content/en/resources.yaml

add Nov resources, fix typo

---

content/en/.gitignore
data/.gitignore
hack/import-calendar.py
layouts/shortcodes/blocks/calendar.html
layouts/shortcodes/blocks/next_event.html

calendar: use data template instead

---

content/en/flux/cheatsheets/bootstrap.md
content/en/flux/cheatsheets/oci-artifacts.md

Add instructions on how to configure persistent storage for source-controller data.

Persistent storage for Flux internal artifacts

---

layouts/adopters/list.html

adopters: Fix hyphenation of names

---

content/en/flux/faq.md

Fix: https://github.com/fluxcd/flux2/issues/3316

FAQ: How can I safely rename a Flux Kustomization?

---

content/en/ecosystem/index.md
content/en/flux/faq.md

make it possible to search for the term 'GUI' as well

---

layouts/partials/hooks/body-end.html

stop loading old Algolia JS

---

assets/scss/_support.scss

support: make svg show up

---

assets/scss/_index.scss
content/en/_index.html
layouts/shortcodes/blocks/contributors.html
layouts/shortcodes/blocks/resources_section.html

- smaller contributor avatars
- drop "other flux projects" section
- show only 3 resources
Ref: #1327

Trim landing page - part 1

---

assets/scss/adopters_wall.scss

resolve https://github.com/fluxcd/website/issues/1317

update adopters-wall scss

---

content/en/flagger/SUMMARY.md
content/en/flagger/_index.md
content/en/flagger/install/flagger-install-on-kubernetes.md
content/en/flagger/tutorials/apisix-progressive-delivery.md
content/en/flagger/usage/deployment-strategies.md

add apache apisix docs for flagger

---

content/en/flux/components/source/options.md

update `--artifact-retention-ttl` flag desc in source-controller docs

---

content/en/flux/components/image/options.md

Add documentation for the new feature gate introduced in https://github.com/fluxcd/image-automation-controller/pull/469.

iac: Add feature gate GitAllBranchReferences

---

content/en/flux/components/helm/options.md

Adding documentation for the new `--graceful-shutdown-timeout` flag.

Document graceful-shutdown-timeout flag

---

content/en/flux/cheatsheets/oci-artifacts.md
content/en/flux/components/notification/options.md
content/en/flux/guides/helmreleases.md
content/en/flux/guides/image-update.md
content/en/flux/guides/monitoring.md
content/en/flux/guides/notifications.md
content/en/flux/guides/webhook-receivers.md
content/en/flux/use-cases/gh-actions-helm-promotion.md
hack/import-flux2-assets.sh

Part of: https://github.com/fluxcd/flux2/issues/3344
⚠️ To be merged after the next Flux release!

Update spec docs to Notification APIs v1beta2

---

.github/workflows/update-contributors.yaml

drop unmaintained pip action

---

content/en/flux/faq.md

I was looking for a way to set helm chart (or image tag)  version separately for each cluster, following the structure in: https://github.com/fluxcd/flux2-kustomize-helm-example.
https://pkg.go.dev/github.com/fluxcd/pkg/apis/kustomize#Image seemed simple for overriding the image, although not the helm chart version, but it doesn't actually work, since we are making kustomization to `HelmRelease`. So I though something like this in the FAQ could be helpful. What do you think?

Add FAQ section regarding overriding HelmRelease values with kustomization

---

MAINTAINERS

I'm [no longer at Weaveworks](https://twitter.com/r6by/status/1615462931004817408) 🦄💖👀

Scott update affiliation

---

layouts/shortcodes/blocks/flux_ui_galleries.html

follow-up to #1359 - deduplicate code

---

content/en/flagger/tutorials/keda-scaledobject.md
content/en/flagger/usage/how-it-works.md
content/en/flagger/usage/metrics.md

Add docs about `primaryScalerConfigs` and token auth for Prometheus.

update flagger docs for v1.28.0

---

content/en/blog/2023-02-01-january-update.md
content/en/flux/_index.md
hack/new-update-post.py
templates/monthly-update.md

Prepare next monthly update

---

content/en/blog/2023-02-14-flux-pulumi-superpowers/index.md

fix left float

---

content/en/flux/security/_index.md

Documents the changes in https://github.com/fluxcd/flux2/pull/3566

security: Add view, edit and admin roles to RBAC docs

---

content/en/flux/cheatsheets/bootstrap.md

Ref: https://github.com/fluxcd/flux2/discussions/3616

Disable Kubernetes cluster role aggregations at bootstrap

---

assets/scss/_index.scss
assets/scss/blocks/_calendar.scss

Calendar: limit session title width, elipsise

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1397

update hugo to v0.111.1

---

assets/scss/blocks/_calendar.scss

resolve https://github.com/fluxcd/website/issues/1402

fix calendar block on mobile

---

content/en/_index.html

resolve https://github.com/fluxcd/website/issues/1405

fix adopters Weaveworks block

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1414

update hugo to v0.111.3

---

content/en/contributing/docs/google-season-of-docs-2023.md

The application process wants a link to our proposal - let's publish it on our website.
Flux mentors: myself and @mewzherder

publish Season of Docs 2023 proposal on website

---

layouts/shortcodes/blocks/hero.html

resolve https://github.com/fluxcd/website/issues/1426

Accessibility add alt to image

---

.github/workflows/update-contributors.yaml

Fix update contributors job permission

---

data/resources.yaml

Added 5 March events from 2023

Add 2023 resources

---

content/en/contributing/docs/google-season-of-docs-2023.md

Made some required corrections.

Corrections

---

content/en/flux/concepts.md

Added new concepts (continuous delivery, continuous deployment, and progressive delivery) to resolve issue #783
Fix: #783

Add CD & PD to concepts page

---

content/en/flagger/tutorials/kuma-progressive-delivery.md

sync changes made in https://github.com/fluxcd/flagger/pull/1402

Update kuma tutorial for flagger docs

---

content/en/_index.html

As people are already on a website about Flux,
this page would just funnel them back again.

Link to Weaveworks homepage

---

content/en/blog/2023-04-01-march-update/index.md

update kubecon panel time

---

content/en/flux/get-started.md

Made some corrections in `get-started.md` file.

minor corrections in get-started.md file

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1505

update hugo to v0.112.4

---

content/en/flux/cmd/_index.md
content/en/flux/components/kustomize/_index.md
content/en/flux/faq.md
content/en/flux/gitops-toolkit/packages.md
content/en/flux/guides/cron-job-image-auth.md
content/en/flux/guides/helmreleases.md
content/en/flux/guides/image-update.md
content/en/flux/guides/mozilla-sops.md
content/en/flux/guides/sealed-secrets.md
content/en/flux/installation.md
content/en/roadmap.md

Part of: https://github.com/fluxcd/flux2/issues/3911

Update docs to Flux RC.4

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1509

update hugo to v0.112.5

---

MAINTAINERS
templates/monthly-update.md

Unfortunately it's already getting clear that I won't have time to continue serving in this capacity, so I'll remove myself from the maintainers list.
It has been a big pleasure and honour to work alongside all of you and I'm very proud of what we achieved together.
Please don't hesitate to get in touch, if I can be of any help. I'll check in on the Slacks every now and then...

Step down as maintainer for Flux Website

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1514

update hugo to v0.112.7

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1518

update hugo to v0.113.0

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1525

update hugo to v0.114.0

---

content/en/flux/security/best-practices.md

For resource isolation and improved reliability we now recommend users to configured Flux sharding instead of fiddling with the namespace watcher which was never meant to be used outside internal testing.

Security: Recommend sharding for resource isolation

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1531

update hugo to v0.114.1

---

content/en/blog/2022-02-14-security-image-provenance/index.md

Given that this blog post shows up on Google, it needs to be updated as cosign 2.0 broke the old instructions.

Update blog post to cosign 2.0

---

content/en/flux/faq.md
content/en/flux/flux-e2e.md
content/en/flux/releases/_index.md
content/en/flux/releases/controllers.md
content/en/flux/releases/packages.md
content/en/flux/releases/procedure.md

Publish docs from https://github.com/fluxcd/flux2/pull/3254

Add releases section

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1540

update hugo to v0.115.1

---

content/en/flux/security/_index.md
content/en/flux/security/slsa-assessment.md

Changes:
- Link to SLSA assessment from security index
- Update instructions to source-controller v1.0.0

Link to SLSA assessment from security index

---

assets/scss/_page.scss
layouts/404.html
layouts/partials/hooks/body-end.html

The page isn't rendered properly (completely empty) with that comment at the top.
Before: https://fluxcd.io/does-not-exist
After: https://deploy-preview-1551--fluxcd.netlify.app/does-not-exist

Fix 404 page

---

content/en/flux/cheatsheets/oci-artifacts.md
content/en/flux/cheatsheets/sharding.md
content/en/flux/cmd/_index.md
content/en/flux/flux-e2e.md
content/en/flux/flux-gh-action.md
content/en/flux/installation.md
content/en/flux/releases/_index.md
content/en/flux/security/_index.md

Add usage examples for running the Flux CLI in GitHub Actions workflows.

Add Flux GitHub Action documentation

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1556

update hugo to v0.115.2

---

content/en/flux/faq.md
content/en/flux/get-started.md
content/en/flux/guides/image-update.md
content/en/flux/migration/flux-v1-automation-migration.md

Various reconcile intervals were set too low, this PR sets sensible interval values so users don't start on the wrong foot and DDOS the various APIs Flux integrates with.

Set sensible interval values

---

content/en/flux/security/slsa-assessment.md

Part of: https://github.com/fluxcd/flux2/issues/4049

Add SBOM provenance verification to SLSA guide

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1565

update hugo to v0.115.3

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1578

update hugo to v0.115.4

---

content/en/flux/installation/bootstrap/bitbucket.md

Made updates in the Bitbucket doc in accordance with the GitHub, GitLab, etc docs as mentioned in https://github.com/fluxcd/website/pull/1573

Refactor Bootstrap Bitbucket doc

---

.github/workflows/build-push-hugo-image.yml
Dockerfile
package-lock.json

We've had this docker serve stuff in the Makefile and it has been broken since some time ago, I am working it out in this branch.

Add golang to hugo-support image

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1595

update hugo to v0.116.1

---

layouts/adopters/list.html
layouts/blog/baseof.html
layouts/page/single.html
layouts/resources/list.html

It was only rendered under /docs but we really want to show it everywhere.

Add archive notice to all pages

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1613

update hugo to v0.117.0

---

content/en/flux/guides/image-update.md
content/en/flux/guides/mozilla-sops.md
content/en/flux/migration/helm-operator-migration.md
content/en/flux/security/secrets-management.md

The report showed me a few errors I committed in #1621
(This PR will not immediately update the website)

Remaining fixes after #1621

---

content/en/_index.html

Graduation now happened more than half a year ago so it's time to announce the next step, GA.

Change hero banner

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1646

update hugo to v0.118.2

---

Dockerfile

This should solve:
* https://github.com/fluxcd/website/actions/runs/6063171310
I am testing it out locally to be sure nothing else did change

fix Dockerfile for hugo-support image

---

content/en/flux/releases/procedure.md

As discussed in https://cloud-native.slack.com/archives/C02JQ9GLP26/p1692276430788379?thread_ts=1692268731.841579&cid=C02JQ9GLP26
[Preview](https://deploy-preview-1653--fluxcd.netlify.app/flux/releases/procedure/#distribution-release-and-eol-notice-update)

Add notice on EOL and release information

---

content/en/ecosystem/index.md

See further information here: https://ocm.software/docs/guides/deploying-applications-with-ocm-and-gitops/#deploy-the-ocm-controller

Include Open-Component-Descriptor in ecosystem

---

content/en/flux/security/_index.md

Before: https://fluxcd.io/flux/security/#scanning-for-cves
After: https://deploy-preview-1678--fluxcd.netlify.app/flux/security/#scanning-for-cves

Link to "release cadence" section from security page

---

data/resources.yaml

Thanks @marcorichetta for contributing this 🥇 
Preview deploy:
* https://deploy-preview-1685--fluxcd.netlify.app/resources/

Add "Introducción a GitOps con Flux" to Resources

---

content/en/flux/guides/mozilla-sops.md

Changes you to your for grammatical correctness.

Single character typo

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1698

update hugo to v0.120.2

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1710

update hugo to v0.120.4

---

netlify.toml

(cherry picked from commit 8e2ed95bc0be486820a88fd0288654716bd45645)

[v2-0] update hugo to v0.120.4

---

content/en/flux/releases/procedure.md

https://deploy-preview-1715--fluxcd.netlify.app/flux/releases/procedure/#distribution-minor-release-website

Document website changes for minor releases

---

content/en/roadmap.md

Ref: https://github.com/fluxcd/flux2/discussions/4444

Add supported versions and release cadence link to roadmap

---

content/en/roadmap.md

Add `HelmChart` and `OCIRepository` tasks, mark as completed drift detection and correction.

Update Helm GA tasks

---

hugo.yaml

Prepare release Flux 2.2 - main branch

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1750

update hugo to v0.121.1

---

content/en/flux/installation/bootstrap/gitea.md

The doc now explicitly mentions the required minimal permissions.

Polish Gitea PAT permission statements

---

netlify.toml

resolve https://github.com/fluxcd/website/issues/1769

update hugo to v0.121.2

---

MAINTAINERS

Update maintainer details for Somtochi

Update maintainer details for Somtochi

---

netlify.toml

(Manual backport of #1790, because the label trigger noticed I added a merge commit, the workflow called me out in https://github.com/fluxcd/website/actions/runs/7688160859/job/20949053159#step:3:35)

[v2-2] update hugo to v0.122.0

---

content/en/ecosystem/index.md

Adding link to fluxcd-kustomize-mutating-webhook

Add fluxcd-kustomize-mutating-webhook to ecosystem

---

data/adopters/1-flux-v2.yaml
static/img/logos/aenix.svg

Hi, we based our free PaaS platform [Cozystack](https://cozystack.io/) on fluxcd to run managed Kubernetes clusters with Cluster-API, Databases-as-a-Service and Virtual Machines.
We'd like to share this information :)

Add Ænix to the Adopters list

---

data/contributors.yaml

Resolved a merge conflict manually, by copying `data/contributors.yaml` from `main` at 1a1c9701
(per https://github.com/fluxcd/website/pull/1834#issuecomment-1973872300)

 [v2-2] Update contributors section

---

hack/contributors.py

Recognize additional repositories that are not currently included in the contributors sources.

Add some repos in contributors.py

---

content/en/roadmap.md

Preview: https://deploy-preview-1847--fluxcd.netlify.app/roadmap/

Define the Flux roadmap for 2024

---

content/en/roadmap.md

Mark completed tasks and include https://github.com/fluxcd/terraform-provider-flux/issues/615

Update Roadmap for Q2

---

content/en/flux/installation/_index.md

Adding links to the terraform provider examples

---

data/adopters/1-flux-v2.yaml
data/adopters/3-flux-v1.yaml

This image URL is 404 on the home page when I checked the JavaScript/Chrome web console

Fix MilliporeSigma.png 404

---

content/en/flux/installation/configuration/openshift.md

Followup: https://github.com/fluxcd/flux2/pull/4729
Fix: https://github.com/fluxcd/flux2/issues/4609

Update OpenShift bootstrap instruction

---

content/en/flux/installation/_index.md
content/en/flux/installation/bootstrap/generic-git-server.md
content/en/flux/installation/bootstrap/oracle-vbs-git-repositories.md

Add bootstrap guide for Oracle VBS Git Repositories

---

content/en/flux/installation/configuration/air-gapped.md

Followup: https://github.com/fluxcd/flux2/pull/4706
Ref: https://github.com/fluxcd/flux2/issues/4621
Fix: #1899
PS. This PR can be merged into main and must be published under `v2-3` branch after Flux v2.3 release.

Improve the air-gapped with `flux bootstrap --registry-creds`

---

content/en/flux/installation/bootstrap/azure-devops.md
content/en/flux/installation/bootstrap/generic-git-server.md

[v2-2] Update Azure DevOps docs with RSA SHA-2 keys

---

content/en/flux/installation/_index.md
content/en/roadmap.md

xref: https://github.com/fluxcd/flux2/pull/4781

Update the roadmap with supported Kubernetes versions

---

content/en/flux/gitops-toolkit/debugging.md
content/en/flux/gitops-toolkit/packages.md
content/en/flux/gitops-toolkit/source-watcher.md

Update API versions in dev guides

Update dev guides to Flux v2.3

---

content/en/flux/cheatsheets/oci-artifacts.md

depends on https://github.com/fluxcd/flux2/issues/4692

Add notation signing and verification

---

content/en/roadmap.md

Add RFCs and feature requests issues.

Update roadmap for Q3

---

content/en/ecosystem/index.md

Fixes error in #1997 merge conflict resolution - sorry!

Ecosystem page

---

content/en/blog/2022-09-14-how-to-gitops-your-terraform/index.md
content/en/blog/2023-04-01-march-update/index.md

resolve https://github.com/fluxcd/website/issues/2004

update blog folder links

---

content/en/contributing/docs/google-season-of-docs-2023.md

resolve https://github.com/fluxcd/website/issues/2011

update contributing folder links

---

data/resources.yaml

Add Lukasz (with Giantswarm) video from CI CD on AWS show from July 1, 2024.

Add new video to resources.yaml

---

data/resources.yaml

Add 2 videos from GitOpsCon NA 2024 to resources. 🙃

Add gitopscon na 2024 videos to resources.yaml

---

content/en/flux/installation/configuration/sharding.md

Update sharding.md with minor spelling changes

---

content/en/flux/monitoring/custom-metrics.md

Fix: https://github.com/fluxcd/flux2/issues/4895

Update custom metrics guide to HelmRelease v2

---

content/en/roadmap.md

This PR updates the roadmap based on the discussions from the dev meeting Wed 31 July 2024.

Update roadmap for Flux v2.4

---

content/en/flux/use-cases/gh-actions-app-builder.md

It's time to review all of these actions use case docs and update them. (WIP)

Update GitHub Actions versions

---

content/en/flux/migration/flux-v1-automation-migration.md

Does what it says on the tin; Resolves `unknown flag: --branch` error from CLI version `v2.3.0`.

Update flux-v1-automation-migration.md to replace deprecated/removed --branch with --{checkout,push}-branch

---

data/adopters/1-flux-v2.yaml
static/img/logos/sylva.svg

We would like Sylva to appear in the list of FluxCD adopters.

add Sylva to adopters

---

.github/labels.yaml
hugo.yaml

Part of: https://github.com/fluxcd/flux2/issues/4947

Prepare Flux 2.4.0 release

---

content/en/roadmap.md

Closes: https://github.com/fluxcd/flux2/issues/4947

Roadmap: Mark 2.4 milestone as completed

---

content/en/flux/guides/mozilla-sops.md

Resolution of https://github.com/fluxcd/kustomize-controller/pull/1286/files/a0c6b08164df5ab165e11a522f44568b95f4da5b#r1867277561

Describing sops encrypted_regex case in docs.

---

assets/scss/_index.scss

resolve https://github.com/fluxcd/website/issues/2117

update Resources block on main page

---

content/en/flux/cheatsheets/oci-artifacts.md

Part of: https://github.com/fluxcd/flux2/issues/5148

Add subsection for Git providers supporting commit status updates

---

content/en/roadmap.md

Closes https://github.com/fluxcd/flux2/issues/5148

Update roadmap with OCI origin revision done

---

content/en/roadmap.md

Mark source controller's Github App Auth implementation as done in roadmap

Mark source controller's Github App Auth implementation as done in rroadmap

---

content/en/_index.html

Part of https://github.com/fluxcd/flux2/issues/5186

Update website banner to 2.5

---

content/en/flux/cheatsheets/oci-artifacts.md

Fix broken link in oci-artifacts.md

---

content/en/flux/guides/helmreleases.md

Little small tweaks to the spelling and wording here.

Small copyediting tweaks

---

content/en/privacy.md
hugo.yaml

fix: https://github.com/fluxcd/website/issues/91
[Preview](https://deploy-preview-2190--fluxcd.netlify.app/privacy/)
I could add this to the footer; not sure if that's needed, but I can if we want to.

Add privacy policy

---

content/en/roadmap.md

Add Git integrations tasks and RFCs.

Update roadmap for Flux v2.6

---

content/en/flux/cheatsheets/oci-artifacts.md
content/en/flux/guides/helmreleases.md

fix: https://github.com/fluxcd/flux2/issues/5329
fix: https://github.com/fluxcd/flux2/issues/5328

Fix podinfo OCI version in docs

---

content/en/flux/components/image/options.md

Part of: https://github.com/fluxcd/flux2/issues/5022

Add token cache flags for image-reflector-controller

---

content/en/roadmap.md

Update the Q2 milestone based on the last dev meeting discussions.

Update roadmap with OCIRepository GA release

---

content/en/roadmap.md

Add `WaitForTermination` feature to Flux 2.6 milestone

Update roadmap with `WaitForTermination` deletion policy

---

content/en/flux/guides/image-update.md

Depends on: https://github.com/fluxcd/image-reflector-controller/pull/368, https://github.com/fluxcd/image-automation-controller/pull/902
Part of: https://github.com/fluxcd/flux2/issues/4245

Add guides for image digest pinning

---

content/en/flux/cheatsheets/oci-artifacts.md
content/en/flux/faq.md
content/en/flux/guides/helmreleases.md

Part of: https://github.com/fluxcd/flux2/issues/5363

Update OCIRepository examples to v1 (GA)

---

content/en/flux/installation/_index.md

xref: https://github.com/fluxcd/flux2/pull/4749

Add Flux Operator as an alternative bootstrap method

---

content/en/blog/2025-05-29-announcing-flux-v2.6.0/index.md

Part of: https://github.com/fluxcd/flux2/issues/5363

Update Flux 2.6 blog post to include breaking changes

---

data/contributors.yaml
hugo.yaml

v2.4 is archived, v2.6 is current

[v2-4] Fix site header

---

data/contributors.yaml
hugo.yaml

v2.5 is archived, v2.6 is current

[v2-5] Fix site header

---

content/en/roadmap.md

Add implemented features and new tasks.

Update roadmap for Flux 2.7

---

content/en/flux/concepts.md

Add Gitless GitOps definition and links

Add Gitless GitOps to core concepts

---

content/en/roadmap.md

Mark completed tasks in the Flux 2.7 milestone

Add OpenTelemetry and ExternalArtifact features to roadmap

---

content/en/roadmap.md

Part of: https://github.com/fluxcd/flux2/issues/5516

Complete 2.7 roadmap

---

.github/labels.yaml
hugo.yaml

This PR should've been automatically opened by the label added in #2367

[v2-5] Prepare Flux v2.7.0 release

---

content/en/flux/cheatsheets/oci-artifacts.md
content/en/flux/guides/image-update.md
content/en/flux/guides/sortable-image-tags.md
content/en/flux/migration/flux-v1-automation-migration.md

Part of: https://github.com/fluxcd/flux2/issues/5516

Update all guides to `image.toolkit.fluxcd.io/v1`

---

content/en/flux/guides/webhook-receivers.md

Update the docs to show how to expose notification-controller webhook receiver using Gateway API.

Add Gateway API example to the webhook receiver guide

---

content/en/blog/2025-09-29-announcing-flux-v2.7.0/index.md
content/en/flux/installation/upgrade.md

Link to https://github.com/fluxcd/flux2/discussions/5572

Link to the Upgrade Procedure for Flux v2.7+
